/* Generated by opensource COBOL 4J 2.0.0 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import jp.osscons.opensourcecobol.libcobj.sql.*;
import java.util.Optional;

public class CCLEGACYX implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return CCLEGACYX_(0, argStorages);
  }

  @Override
  public void cancel() {
    CCLEGACYX_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int CCLEGACYX_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("CCLEGACYX");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("CCLEGACYX");

      b_RETURN_CODE.set((int)0);
      b_WS_CODE__WS_AREA.fillBytes(' ', 2);
      CobolFieldFactory.makeCobolField(5, b_WS_AMOUNT__WS_AREA, a_1_NumericPacked_Digits9_Scale2_HaveSign).setZero ();

      b_WS_FLAGS__WS_AREA.fillBytes(' ', 10);
      b_WS_INDEX.set((byte)1);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_CCLEGACYX);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_CCLEGACYX]);
      }
    },
    /* Entry CCLEGACYX */
    new CobolControl(l_CCLEGACYX, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__0000_START]);
      }
    },
    /* 0000-START */
    new CobolControl(l_MAIN_SECTION__0000_START, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCLEGACYX.cob:14: PERFORM */
        /* PERFORM 1000-VALIDATE THRU 1000-EXIT */
        CobolControl.performThrough(contList, 
l_MAIN_SECTION__1000_VALIDATE, l_MAIN_SECTION__1000_EXIT).run();
        /* src/CCLEGACYX.cob:15: GO TO */
        {
          if(true) return Optional.of(contList[l_MAIN_SECTION__9000_END]);
        }

        return Optional.of(contList[l_MAIN_SECTION__1000_VALIDATE]);
      }
    },
    /* 1000-VALIDATE */
    new CobolControl(l_MAIN_SECTION__1000_VALIDATE, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCLEGACYX.cob:17: EVALUATE */
        {
          if (((long)b_WS_CODE__WS_AREA.memcmp (str_0_MV, 2) == 0L))
            {
              /* src/CCLEGACYX.cob:18: MOVE */
              {
                b_WS_CODE__WS_AREA.setBytes (str_1_MO, 2);
              }
            }
          else
            if (((long)b_WS_CODE__WS_AREA.memcmp (str_2_HE, 2) == 0L))
              {
                /* src/CCLEGACYX.cob:19: MOVE */
                {
                  b_WS_CODE__WS_AREA.setBytes (str_3_HE, 2);
                }
              }
            else
              {
                /* src/CCLEGACYX.cob:20: MOVE */
                {
                  b_WS_CODE__WS_AREA.fillBytes (88, 2);
                }
              }
        }
        /* src/CCLEGACYX.cob:22: PERFORM */
        b_WS_INDEX.set((byte)1);
        for(;;b_WS_INDEX.addU8Binary (1))
        {
          if (((long)f_WS_INDEX.cmpInteger (10) >  0L))
            break;
          {
            /* src/CCLEGACYX.cob:24: MOVE */
            {
              b_WS_FLAG__WS_FLAG_TABLE__WS_AREA.getSubDataStorage((b_WS_INDEX.getByte(0) - 1)).setByte(89);
            }
          }
        }

        return Optional.of(contList[l_MAIN_SECTION__1000_EXIT]);
      }
    },
    /* 1000-EXIT */
    new CobolControl(l_MAIN_SECTION__1000_EXIT, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCLEGACYX.cob:27: EXIT */

        return Optional.of(contList[l_MAIN_SECTION__9000_END]);
      }
    },
    /* 9000-END */
    new CobolControl(l_MAIN_SECTION__9000_END, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCLEGACYX.cob:29: GOBACK */
        {
          if(true) return Optional.of(contList[contList.length - 1]);
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new CCLEGACYX().CCLEGACYX_(0);
    CobolStopRunException.stopRun();
  }

  public CCLEGACYX()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : CCLEGACYX */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_WS_AREA = new CobolDataStorage(17);	/* WS-AREA */
    b_WS_INDEX = new CobolDataStorage(1);	/* WS-INDEX */
    b_WS_AMOUNT__WS_AREA = b_WS_AREA.getSubDataStorage(2);
    b_WS_CODE__WS_AREA = b_WS_AREA;
    b_WS_FLAG__WS_FLAG_TABLE__WS_AREA = b_WS_AREA.getSubDataStorage(7);
    b_WS_FLAGS__WS_AREA = b_WS_AREA.getSubDataStorage(7);

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : CCLEGACYX */
    f_WS_INDEX	= CobolFieldFactory.makeCobolField(1, b_WS_INDEX, a_2_NumericBinary_Digits2_Scale0_BinarySwap);	/* WS-INDEX */

    /* End of fields */


  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericPacked_Digits9_Scale2_HaveSign = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_PACKED,
      /* digits= */ 9,
      /* scale= */ 2,
      CobolFieldAttribute.COB_FLAG_HAVE_SIGN,
      /* pic= */ null);
    a_2_NumericBinary_Digits2_Scale0_BinarySwap = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_BINARY,
      /* digits= */ 2,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_BINARY_SWAP,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : CCLEGACYX */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_WS_AREA;	/* WS-AREA */
  private CobolDataStorage b_WS_INDEX;	/* WS-INDEX */
  private CobolDataStorage b_WS_AMOUNT__WS_AREA;
  private CobolDataStorage b_WS_CODE__WS_AREA;
  private CobolDataStorage b_WS_FLAG__WS_FLAG_TABLE__WS_AREA;
  private CobolDataStorage b_WS_FLAGS__WS_AREA;

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : CCLEGACYX */
  private AbstractCobolField f_WS_INDEX;	/* WS-INDEX */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Attributes */

  private CobolFieldAttribute a_2_NumericBinary_Digits2_Scale0_BinarySwap;
  private CobolFieldAttribute a_1_NumericPacked_Digits9_Scale2_HaveSign;



  /* String literals */
  public static final byte[] str_3_HE = CobolUtil.stringToBytes("HE");
  public static final byte[] str_2_HE = CobolUtil.stringToBytes("HE");
  public static final byte[] str_1_MO = CobolUtil.stringToBytes("MO");
  public static final byte[] str_0_MV = CobolUtil.stringToBytes("MV");

  /* Sections and Labels */
  private final static int l_CCLEGACYX = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__0000_START = 3;
  private final static int l_MAIN_SECTION__1000_VALIDATE = 4;
  private final static int l_MAIN_SECTION__1000_EXIT = 5;
  private final static int l_MAIN_SECTION__9000_END = 6;
  private final static int l_Default_Error_Handler = 7;

}
