/* Generated by opensource COBOL 4J 2.0.0 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import jp.osscons.opensourcecobol.libcobj.sql.*;
import java.util.Optional;

public class CCLOAD01 implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return CCLOAD01_(0, argStorages);
  }

  @Override
  public void cancel() {
    CCLOAD01_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int CCLOAD01_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	h_POLICY_MASTER.close (0, null);
    	h_CUSTOMER_MASTER.close (0, null);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("CCLOAD01");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("CCLOAD01");

      b_RETURN_CODE.set((int)0);
      b_WS_POL_STATUS.fillBytes(' ', 2);
      b_WS_CUS_STATUS.fillBytes(' ', 2);

      if (k_POLICY_MASTER == null)
      {
        k_POLICY_MASTER = new CobolFileKey[1];
        for (int i=0; i<1; ++i)
          k_POLICY_MASTER[i] = new CobolFileKey();
      }
      k_POLICY_MASTER[0].setField(f_POL_POLICY_ID__POLICY_RECORD);
      k_POLICY_MASTER[0].setFlag(0);
      k_POLICY_MASTER[0].setOffset(0);
      h_POLICY_MASTER = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "POLICY-MASTER",
      /* file_status = */ h_POLICY_MASTER_status,
      /* assign = */ c_1_data,
      /* record = */ f_POLICY_MASTER_record,
      /* record_size = */ null,
      /* record_min = */ 71,
      /* record_max = */ 71,
      /* nkeys = */ 1,
      /* keys = */ k_POLICY_MASTER,
      /* organization = */ (char)3,
      /* access_mode = */ (char)2,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)0,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)1,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );
      if (k_CUSTOMER_MASTER == null)
      {
        k_CUSTOMER_MASTER = new CobolFileKey[1];
        for (int i=0; i<1; ++i)
          k_CUSTOMER_MASTER[i] = new CobolFileKey();
      }
      k_CUSTOMER_MASTER[0].setField(f_CUS_CUSTOMER_ID__CUSTOMER_RECORD);
      k_CUSTOMER_MASTER[0].setFlag(0);
      k_CUSTOMER_MASTER[0].setOffset(0);
      h_CUSTOMER_MASTER = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "CUSTOMER-MASTER",
      /* file_status = */ h_CUSTOMER_MASTER_status,
      /* assign = */ c_2_data,
      /* record = */ f_CUSTOMER_MASTER_record,
      /* record_size = */ null,
      /* record_min = */ 80,
      /* record_max = */ 80,
      /* nkeys = */ 1,
      /* keys = */ k_CUSTOMER_MASTER,
      /* organization = */ (char)3,
      /* access_mode = */ (char)2,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)0,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)1,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );

      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_CCLOAD01);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_CCLOAD01]);
      }
    },
    /* Entry CCLOAD01 */
    new CobolControl(l_CCLOAD01, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN_SECTION]);
      }
    },
    /* MAIN-SECTION */
    new CobolControl(l_MAIN_SECTION__MAIN_SECTION, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCLOAD01.cob:23: OPEN */
        {
          CobolRuntimeException.code = 0;
          {
            h_POLICY_MASTER.open (2, 1, f_WS_POL_STATUS);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
          CobolRuntimeException.code = 0;
          {
            h_CUSTOMER_MASTER.open (2, 1, f_WS_CUS_STATUS);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* src/CCLOAD01.cob:24: PERFORM */
        /* PERFORM LOAD-CUSTOMERS */
        CobolControl.perform(contList, l_MAIN_SECTION__LOAD_CUSTOMERS).run();
        /* src/CCLOAD01.cob:25: PERFORM */
        /* PERFORM LOAD-POLICIES */
        CobolControl.perform(contList, l_MAIN_SECTION__LOAD_POLICIES).run();
        /* src/CCLOAD01.cob:26: CLOSE */
        {
          CobolRuntimeException.code = 0;
          {
            h_POLICY_MASTER.close (0, f_WS_POL_STATUS);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
          CobolRuntimeException.code = 0;
          {
            h_CUSTOMER_MASTER.close (0, f_WS_CUS_STATUS);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* src/CCLOAD01.cob:27: MOVE */
        {
          b_RETURN_CODE.set((int)0);
        }
        /* src/CCLOAD01.cob:28: GOBACK */
        {
          if(true) return Optional.of(contList[contList.length - 1]);
        }

        return Optional.of(contList[l_MAIN_SECTION__LOAD_CUSTOMERS]);
      }
    },
    /* LOAD-CUSTOMERS */
    new CobolControl(l_MAIN_SECTION__LOAD_CUSTOMERS, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCLOAD01.cob:30: INITIALIZE */
        {
          b_CUSTOMER_RECORD.fillBytes(' ', 80);
        }
        /* src/CCLOAD01.cob:31: MOVE */
        {
          b_CUS_CUSTOMER_ID__CUSTOMER_RECORD.setBytes (str_0_U00001, 6);
        }
        /* src/CCLOAD01.cob:32: MOVE */
        {
          b_CUS_NAME__CUSTOMER_RECORD.setBytes (str_1_GLOBAL, 30);
        }
        /* src/CCLOAD01.cob:33: MOVE */
        {
          b_CUS_STATUS__CUSTOMER_RECORD.setByte(65);
        }
        /* src/CCLOAD01.cob:33: MOVE */
        {
          b_CUS_CITY__CUSTOMER_RECORD.setBytes (str_2_HYDERABAD, 20);
        }
        /* src/CCLOAD01.cob:34: MOVE */
        {
          b_CUS_STATE__CUSTOMER_RECORD.setBytes (str_3_TS, 2);
        }
        /* src/CCLOAD01.cob:34: MOVE */
        {
          b_CUS_RISK_LEVEL__CUSTOMER_RECORD.setByte(76);
        }
        /* src/CCLOAD01.cob:35: WRITE */
        CobolRuntimeException.code = 0;
        {
          h_CUSTOMER_MASTER.write (f_CUSTOMER_RECORD, 0, f_WS_CUS_STATUS);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }
        /* src/CCLOAD01.cob:36: INITIALIZE */
        {
          b_CUSTOMER_RECORD.fillBytes(' ', 80);
        }
        /* src/CCLOAD01.cob:37: MOVE */
        {
          b_CUS_CUSTOMER_ID__CUSTOMER_RECORD.setBytes (str_4_U00002, 6);
        }
        /* src/CCLOAD01.cob:38: MOVE */
        {
          b_CUS_NAME__CUSTOMER_RECORD.setBytes (str_5_SUNRISE, 30);
        }
        /* src/CCLOAD01.cob:39: MOVE */
        {
          b_CUS_STATUS__CUSTOMER_RECORD.setByte(65);
        }
        /* src/CCLOAD01.cob:39: MOVE */
        {
          b_CUS_CITY__CUSTOMER_RECORD.setBytes (str_6_VIJAYAWADA, 20);
        }
        /* src/CCLOAD01.cob:40: MOVE */
        {
          b_CUS_STATE__CUSTOMER_RECORD.setBytes (str_7_AP, 2);
        }
        /* src/CCLOAD01.cob:40: MOVE */
        {
          b_CUS_RISK_LEVEL__CUSTOMER_RECORD.setByte(77);
        }
        /* src/CCLOAD01.cob:41: WRITE */
        CobolRuntimeException.code = 0;
        {
          h_CUSTOMER_MASTER.write (f_CUSTOMER_RECORD, 0, f_WS_CUS_STATUS);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }
        /* src/CCLOAD01.cob:42: INITIALIZE */
        {
          b_CUSTOMER_RECORD.fillBytes(' ', 80);
        }
        /* src/CCLOAD01.cob:43: MOVE */
        {
          b_CUS_CUSTOMER_ID__CUSTOMER_RECORD.setBytes (str_8_U00003, 6);
        }
        /* src/CCLOAD01.cob:44: MOVE */
        {
          b_CUS_NAME__CUSTOMER_RECORD.setBytes (str_9_ORBIT, 30);
        }
        /* src/CCLOAD01.cob:45: MOVE */
        {
          b_CUS_STATUS__CUSTOMER_RECORD.setByte(65);
        }
        /* src/CCLOAD01.cob:45: MOVE */
        {
          b_CUS_CITY__CUSTOMER_RECORD.setBytes (str_10_CHENNAI, 20);
        }
        /* src/CCLOAD01.cob:46: MOVE */
        {
          b_CUS_STATE__CUSTOMER_RECORD.setBytes (str_11_TN, 2);
        }
        /* src/CCLOAD01.cob:46: MOVE */
        {
          b_CUS_RISK_LEVEL__CUSTOMER_RECORD.setByte(72);
        }
        /* src/CCLOAD01.cob:47: WRITE */
        CobolRuntimeException.code = 0;
        {
          h_CUSTOMER_MASTER.write (f_CUSTOMER_RECORD, 0, f_WS_CUS_STATUS);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }

        return Optional.of(contList[l_MAIN_SECTION__LOAD_POLICIES]);
      }
    },
    /* LOAD-POLICIES */
    new CobolControl(l_MAIN_SECTION__LOAD_POLICIES, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCLOAD01.cob:49: INITIALIZE */
        {
          b_POL_POLICY_ID__POLICY_RECORD.fillBytes(' ', 22);
          f_POL_COVER_LIMIT__POLICY_RECORD.setZero ();

          f_POL_DEDUCTIBLE__POLICY_RECORD.setZero ();

          b_POL_EFFECTIVE_DATE__POLICY_RECORD.fillBytes('0', 16);
          b_POL_RESERVED__POLICY_RECORD.fillBytes(' ', 20);
        }
        /* src/CCLOAD01.cob:50: MOVE */
        {
          b_POL_POLICY_ID__POLICY_RECORD.setBytes (str_12_PL00000001, 10);
        }
        /* src/CCLOAD01.cob:51: MOVE */
        {
          b_POL_CUSTOMER_ID__POLICY_RECORD.setBytes (str_13_U00001, 6);
        }
        /* src/CCLOAD01.cob:51: MOVE */
        {
          b_POL_TYPE__POLICY_RECORD.setBytes (str_14_MV, 2);
        }
        /* src/CCLOAD01.cob:52: MOVE */
        {
          b_POL_STATUS__POLICY_RECORD.setByte(65);
        }
        /* src/CCLOAD01.cob:52: MOVE */
        {
          b_POL_CURRENCY__POLICY_RECORD.setBytes (str_15_INR, 3);
        }
        /* src/CCLOAD01.cob:53: MOVE */
        {
          f_POL_COVER_LIMIT__POLICY_RECORD.moveFrom (c_3_50000000);
        }
        /* src/CCLOAD01.cob:53: MOVE */
        {
          f_POL_DEDUCTIBLE__POLICY_RECORD.moveFrom (c_4_2500000);
        }
        /* src/CCLOAD01.cob:54: MOVE */
        {
          b_POL_EFFECTIVE_DATE__POLICY_RECORD.setBytes (str_16_20260101, 8);
        }
        /* src/CCLOAD01.cob:54: MOVE */
        {
          b_POL_EXPIRY_DATE__POLICY_RECORD.setBytes (str_17_20261231, 8);
        }
        /* src/CCLOAD01.cob:55: WRITE */
        CobolRuntimeException.code = 0;
        {
          h_POLICY_MASTER.write (f_POLICY_RECORD, 0, f_WS_POL_STATUS);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }
        /* src/CCLOAD01.cob:56: INITIALIZE */
        {
          b_POL_POLICY_ID__POLICY_RECORD.fillBytes(' ', 22);
          f_POL_COVER_LIMIT__POLICY_RECORD.setZero ();

          f_POL_DEDUCTIBLE__POLICY_RECORD.setZero ();

          b_POL_EFFECTIVE_DATE__POLICY_RECORD.fillBytes('0', 16);
          b_POL_RESERVED__POLICY_RECORD.fillBytes(' ', 20);
        }
        /* src/CCLOAD01.cob:57: MOVE */
        {
          b_POL_POLICY_ID__POLICY_RECORD.setBytes (str_18_PL00000002, 10);
        }
        /* src/CCLOAD01.cob:58: MOVE */
        {
          b_POL_CUSTOMER_ID__POLICY_RECORD.setBytes (str_19_U00002, 6);
        }
        /* src/CCLOAD01.cob:58: MOVE */
        {
          b_POL_TYPE__POLICY_RECORD.setBytes (str_20_HE, 2);
        }
        /* src/CCLOAD01.cob:59: MOVE */
        {
          b_POL_STATUS__POLICY_RECORD.setByte(65);
        }
        /* src/CCLOAD01.cob:59: MOVE */
        {
          b_POL_CURRENCY__POLICY_RECORD.setBytes (str_21_INR, 3);
        }
        /* src/CCLOAD01.cob:60: MOVE */
        {
          f_POL_COVER_LIMIT__POLICY_RECORD.moveFrom (c_5_30000000);
        }
        /* src/CCLOAD01.cob:60: MOVE */
        {
          f_POL_DEDUCTIBLE__POLICY_RECORD.moveFrom (c_6_1000000);
        }
        /* src/CCLOAD01.cob:61: MOVE */
        {
          b_POL_EFFECTIVE_DATE__POLICY_RECORD.setBytes (str_22_20260101, 8);
        }
        /* src/CCLOAD01.cob:61: MOVE */
        {
          b_POL_EXPIRY_DATE__POLICY_RECORD.setBytes (str_23_20261231, 8);
        }
        /* src/CCLOAD01.cob:62: WRITE */
        CobolRuntimeException.code = 0;
        {
          h_POLICY_MASTER.write (f_POLICY_RECORD, 0, f_WS_POL_STATUS);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }
        /* src/CCLOAD01.cob:63: INITIALIZE */
        {
          b_POL_POLICY_ID__POLICY_RECORD.fillBytes(' ', 22);
          f_POL_COVER_LIMIT__POLICY_RECORD.setZero ();

          f_POL_DEDUCTIBLE__POLICY_RECORD.setZero ();

          b_POL_EFFECTIVE_DATE__POLICY_RECORD.fillBytes('0', 16);
          b_POL_RESERVED__POLICY_RECORD.fillBytes(' ', 20);
        }
        /* src/CCLOAD01.cob:64: MOVE */
        {
          b_POL_POLICY_ID__POLICY_RECORD.setBytes (str_24_PL00000003, 10);
        }
        /* src/CCLOAD01.cob:65: MOVE */
        {
          b_POL_CUSTOMER_ID__POLICY_RECORD.setBytes (str_25_U00003, 6);
        }
        /* src/CCLOAD01.cob:65: MOVE */
        {
          b_POL_TYPE__POLICY_RECORD.setBytes (str_26_PR, 2);
        }
        /* src/CCLOAD01.cob:66: MOVE */
        {
          b_POL_STATUS__POLICY_RECORD.setByte(69);
        }
        /* src/CCLOAD01.cob:66: MOVE */
        {
          b_POL_CURRENCY__POLICY_RECORD.setBytes (str_27_INR, 3);
        }
        /* src/CCLOAD01.cob:67: MOVE */
        {
          f_POL_COVER_LIMIT__POLICY_RECORD.moveFrom (c_7_15000000);
        }
        /* src/CCLOAD01.cob:67: MOVE */
        {
          f_POL_DEDUCTIBLE__POLICY_RECORD.moveFrom (c_8_1500000);
        }
        /* src/CCLOAD01.cob:68: MOVE */
        {
          b_POL_EFFECTIVE_DATE__POLICY_RECORD.setBytes (str_28_20250101, 8);
        }
        /* src/CCLOAD01.cob:68: MOVE */
        {
          b_POL_EXPIRY_DATE__POLICY_RECORD.setBytes (str_29_20251231, 8);
        }
        /* src/CCLOAD01.cob:69: WRITE */
        CobolRuntimeException.code = 0;
        {
          h_POLICY_MASTER.write (f_POLICY_RECORD, 0, f_WS_POL_STATUS);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }


        return Optional.of(CobolControl.pure());
      }
    },
    /* Default Error Handler */
    new CobolControl(l_Default_Error_Handler, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        if ((CobolFile.errorFile.flag_select_features & CobolFile.COB_SELECT_FILE_STATUS) == 0) {
        	CobolFile.defaultErrorHandle ();
        	CobolStopRunException.stopRunAndThrow (1);
        }

        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new CCLOAD01().CCLOAD01_(0);
    CobolStopRunException.stopRun();
  }

  public CCLOAD01()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : CCLOAD01 */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_POLICY_MASTER_record = new CobolDataStorage(71);	/* POLICY-MASTER_record */
    b_CUSTOMER_MASTER_record = new CobolDataStorage(80);	/* CUSTOMER-MASTER_record */
    b_WS_POL_STATUS = new CobolDataStorage(2);	/* WS-POL-STATUS */
    b_WS_CUS_STATUS = new CobolDataStorage(2);	/* WS-CUS-STATUS */
    b_CUS_CITY__CUSTOMER_RECORD = b_CUSTOMER_MASTER_record.getSubDataStorage(37);
    b_CUS_CUSTOMER_ID__CUSTOMER_RECORD = b_CUSTOMER_MASTER_record;
    b_CUS_NAME__CUSTOMER_RECORD = b_CUSTOMER_MASTER_record.getSubDataStorage(6);
    b_CUS_RISK_LEVEL__CUSTOMER_RECORD = b_CUSTOMER_MASTER_record.getSubDataStorage(59);
    b_CUS_STATE__CUSTOMER_RECORD = b_CUSTOMER_MASTER_record.getSubDataStorage(57);
    b_CUS_STATUS__CUSTOMER_RECORD = b_CUSTOMER_MASTER_record.getSubDataStorage(36);
    b_CUSTOMER_RECORD = b_CUSTOMER_MASTER_record;
    b_POL_COVER_LIMIT__POLICY_RECORD = b_POLICY_MASTER_record.getSubDataStorage(22);
    b_POL_CURRENCY__POLICY_RECORD = b_POLICY_MASTER_record.getSubDataStorage(19);
    b_POL_CUSTOMER_ID__POLICY_RECORD = b_POLICY_MASTER_record.getSubDataStorage(10);
    b_POL_DEDUCTIBLE__POLICY_RECORD = b_POLICY_MASTER_record.getSubDataStorage(29);
    b_POL_EFFECTIVE_DATE__POLICY_RECORD = b_POLICY_MASTER_record.getSubDataStorage(35);
    b_POL_EXPIRY_DATE__POLICY_RECORD = b_POLICY_MASTER_record.getSubDataStorage(43);
    b_POL_POLICY_ID__POLICY_RECORD = b_POLICY_MASTER_record;
    b_POL_RESERVED__POLICY_RECORD = b_POLICY_MASTER_record.getSubDataStorage(51);
    b_POL_STATUS__POLICY_RECORD = b_POLICY_MASTER_record.getSubDataStorage(18);
    b_POL_TYPE__POLICY_RECORD = b_POLICY_MASTER_record.getSubDataStorage(16);
    b_POLICY_RECORD = b_POLICY_MASTER_record;

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : CCLOAD01 */
    f_POLICY_RECORD	= CobolFieldFactory.makeCobolField(71, b_POLICY_RECORD, a_2_Group);	/* POLICY-RECORD */
    f_POL_POLICY_ID__POLICY_RECORD	= CobolFieldFactory.makeCobolField(10, b_POL_POLICY_ID__POLICY_RECORD, a_1_Alphanumeric);	/* POL-POLICY-ID */
    f_POL_COVER_LIMIT__POLICY_RECORD	= CobolFieldFactory.makeCobolField(7, b_POL_COVER_LIMIT__POLICY_RECORD, a_3_NumericPacked_Digits13_Scale2_HaveSign);	/* POL-COVER-LIMIT */
    f_POL_DEDUCTIBLE__POLICY_RECORD	= CobolFieldFactory.makeCobolField(6, b_POL_DEDUCTIBLE__POLICY_RECORD, a_4_NumericPacked_Digits11_Scale2_HaveSign);	/* POL-DEDUCTIBLE */
    f_POLICY_MASTER_record	= CobolFieldFactory.makeCobolField(71, b_POLICY_MASTER_record, a_1_Alphanumeric);	/* POLICY-MASTER_record */
    f_CUSTOMER_RECORD	= CobolFieldFactory.makeCobolField(80, b_CUSTOMER_RECORD, a_2_Group);	/* CUSTOMER-RECORD */
    f_CUS_CUSTOMER_ID__CUSTOMER_RECORD	= CobolFieldFactory.makeCobolField(6, b_CUS_CUSTOMER_ID__CUSTOMER_RECORD, a_1_Alphanumeric);	/* CUS-CUSTOMER-ID */
    f_CUSTOMER_MASTER_record	= CobolFieldFactory.makeCobolField(80, b_CUSTOMER_MASTER_record, a_1_Alphanumeric);	/* CUSTOMER-MASTER_record */
    f_WS_POL_STATUS	= CobolFieldFactory.makeCobolField(2, b_WS_POL_STATUS, a_1_Alphanumeric);	/* WS-POL-STATUS */
    f_WS_CUS_STATUS	= CobolFieldFactory.makeCobolField(2, b_WS_CUS_STATUS, a_1_Alphanumeric);	/* WS-CUS-STATUS */

    /* End of fields */


    /* Constants */

    c_1_data	= CobolFieldFactory.makeCobolField(str_30_data, a_1_Alphanumeric);
    c_2_data	= CobolFieldFactory.makeCobolField(str_31_data, a_1_Alphanumeric);
    c_3_50000000	= CobolFieldFactory.makeCobolField(8, "50000000", a_5_NumericDisplay_Digits8_Scale2);
    c_4_2500000	= CobolFieldFactory.makeCobolField(7, "2500000", a_6_NumericDisplay_Digits7_Scale2);
    c_5_30000000	= CobolFieldFactory.makeCobolField(8, "30000000", a_5_NumericDisplay_Digits8_Scale2);
    c_6_1000000	= CobolFieldFactory.makeCobolField(7, "1000000", a_6_NumericDisplay_Digits7_Scale2);
    c_7_15000000	= CobolFieldFactory.makeCobolField(8, "15000000", a_5_NumericDisplay_Digits8_Scale2);
    c_8_1500000	= CobolFieldFactory.makeCobolField(7, "1500000", a_6_NumericDisplay_Digits7_Scale2);

  }

  private void initAttr() {
    /* Attributes */

    a_1_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_Group = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_GROUP,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericPacked_Digits13_Scale2_HaveSign = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_PACKED,
      /* digits= */ 13,
      /* scale= */ 2,
      CobolFieldAttribute.COB_FLAG_HAVE_SIGN,
      /* pic= */ null);
    a_4_NumericPacked_Digits11_Scale2_HaveSign = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_PACKED,
      /* digits= */ 11,
      /* scale= */ 2,
      CobolFieldAttribute.COB_FLAG_HAVE_SIGN,
      /* pic= */ null);
    a_5_NumericDisplay_Digits8_Scale2 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 8,
      /* scale= */ 2,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_6_NumericDisplay_Digits7_Scale2 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 7,
      /* scale= */ 2,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : CCLOAD01 */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_POLICY_MASTER_record;	/* POLICY-MASTER_record */
  private CobolDataStorage b_CUSTOMER_MASTER_record;	/* CUSTOMER-MASTER_record */
  private CobolDataStorage b_WS_POL_STATUS;	/* WS-POL-STATUS */
  private CobolDataStorage b_WS_CUS_STATUS;	/* WS-CUS-STATUS */
  private CobolDataStorage b_CUS_CITY__CUSTOMER_RECORD;
  private CobolDataStorage b_CUS_CUSTOMER_ID__CUSTOMER_RECORD;
  private CobolDataStorage b_CUS_NAME__CUSTOMER_RECORD;
  private CobolDataStorage b_CUS_RISK_LEVEL__CUSTOMER_RECORD;
  private CobolDataStorage b_CUS_STATE__CUSTOMER_RECORD;
  private CobolDataStorage b_CUS_STATUS__CUSTOMER_RECORD;
  private CobolDataStorage b_CUSTOMER_RECORD;
  private CobolDataStorage b_POL_COVER_LIMIT__POLICY_RECORD;
  private CobolDataStorage b_POL_CURRENCY__POLICY_RECORD;
  private CobolDataStorage b_POL_CUSTOMER_ID__POLICY_RECORD;
  private CobolDataStorage b_POL_DEDUCTIBLE__POLICY_RECORD;
  private CobolDataStorage b_POL_EFFECTIVE_DATE__POLICY_RECORD;
  private CobolDataStorage b_POL_EXPIRY_DATE__POLICY_RECORD;
  private CobolDataStorage b_POL_POLICY_ID__POLICY_RECORD;
  private CobolDataStorage b_POL_RESERVED__POLICY_RECORD;
  private CobolDataStorage b_POL_STATUS__POLICY_RECORD;
  private CobolDataStorage b_POL_TYPE__POLICY_RECORD;
  private CobolDataStorage b_POLICY_RECORD;

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : CCLOAD01 */
  private AbstractCobolField f_POLICY_RECORD;	/* POLICY-RECORD */
  private AbstractCobolField f_POL_POLICY_ID__POLICY_RECORD;	/* POL-POLICY-ID */
  private AbstractCobolField f_POL_COVER_LIMIT__POLICY_RECORD;	/* POL-COVER-LIMIT */
  private AbstractCobolField f_POL_DEDUCTIBLE__POLICY_RECORD;	/* POL-DEDUCTIBLE */
  private AbstractCobolField f_POLICY_MASTER_record;	/* POLICY-MASTER_record */
  private AbstractCobolField f_CUSTOMER_RECORD;	/* CUSTOMER-RECORD */
  private AbstractCobolField f_CUS_CUSTOMER_ID__CUSTOMER_RECORD;	/* CUS-CUSTOMER-ID */
  private AbstractCobolField f_CUSTOMER_MASTER_record;	/* CUSTOMER-MASTER_record */
  private AbstractCobolField f_WS_POL_STATUS;	/* WS-POL-STATUS */
  private AbstractCobolField f_WS_CUS_STATUS;	/* WS-CUS-STATUS */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_8_1500000;
  private AbstractCobolField c_7_15000000;
  private AbstractCobolField c_6_1000000;
  private AbstractCobolField c_5_30000000;
  private AbstractCobolField c_4_2500000;
  private AbstractCobolField c_3_50000000;
  private AbstractCobolField c_2_data;
  private AbstractCobolField c_1_data;

  /* Attributes */

  private CobolFieldAttribute a_6_NumericDisplay_Digits7_Scale2;
  private CobolFieldAttribute a_5_NumericDisplay_Digits8_Scale2;
  private CobolFieldAttribute a_4_NumericPacked_Digits11_Scale2_HaveSign;
  private CobolFieldAttribute a_3_NumericPacked_Digits13_Scale2_HaveSign;
  private CobolFieldAttribute a_2_Group;
  private CobolFieldAttribute a_1_Alphanumeric;



  /* String literals */
  public static final byte[] str_31_data = CobolUtil.stringToBytes("data/work/customer.dat");
  public static final byte[] str_30_data = CobolUtil.stringToBytes("data/work/policy.dat");
  public static final byte[] str_29_20251231 = CobolUtil.stringToBytes("20251231");
  public static final byte[] str_28_20250101 = CobolUtil.stringToBytes("20250101");
  public static final byte[] str_27_INR = CobolUtil.stringToBytes("INR");
  public static final byte[] str_26_PR = CobolUtil.stringToBytes("PR");
  public static final byte[] str_25_U00003 = CobolUtil.stringToBytes("U00003");
  public static final byte[] str_24_PL00000003 = CobolUtil.stringToBytes("PL00000003");
  public static final byte[] str_23_20261231 = CobolUtil.stringToBytes("20261231");
  public static final byte[] str_22_20260101 = CobolUtil.stringToBytes("20260101");
  public static final byte[] str_21_INR = CobolUtil.stringToBytes("INR");
  public static final byte[] str_20_HE = CobolUtil.stringToBytes("HE");
  public static final byte[] str_19_U00002 = CobolUtil.stringToBytes("U00002");
  public static final byte[] str_18_PL00000002 = CobolUtil.stringToBytes("PL00000002");
  public static final byte[] str_17_20261231 = CobolUtil.stringToBytes("20261231");
  public static final byte[] str_16_20260101 = CobolUtil.stringToBytes("20260101");
  public static final byte[] str_15_INR = CobolUtil.stringToBytes("INR");
  public static final byte[] str_14_MV = CobolUtil.stringToBytes("MV");
  public static final byte[] str_13_U00001 = CobolUtil.stringToBytes("U00001");
  public static final byte[] str_12_PL00000001 = CobolUtil.stringToBytes("PL00000001");
  public static final byte[] str_11_TN = CobolUtil.stringToBytes("TN");
  public static final byte[] str_10_CHENNAI = CobolUtil.stringToBytes("CHENNAI             ");
  public static final byte[] str_9_ORBIT = CobolUtil.stringToBytes("ORBIT TECHNOLOGIES            ");
  public static final byte[] str_8_U00003 = CobolUtil.stringToBytes("U00003");
  public static final byte[] str_7_AP = CobolUtil.stringToBytes("AP");
  public static final byte[] str_6_VIJAYAWADA = CobolUtil.stringToBytes("VIJAYAWADA          ");
  public static final byte[] str_5_SUNRISE = CobolUtil.stringToBytes("SUNRISE RETAIL GROUP          ");
  public static final byte[] str_4_U00002 = CobolUtil.stringToBytes("U00002");
  public static final byte[] str_3_TS = CobolUtil.stringToBytes("TS");
  public static final byte[] str_2_HYDERABAD = CobolUtil.stringToBytes("HYDERABAD           ");
  public static final byte[] str_1_GLOBAL = CobolUtil.stringToBytes("GLOBAL MOTORS INDIA           ");
  public static final byte[] str_0_U00001 = CobolUtil.stringToBytes("U00001");
  /* File POLICY-MASTER */
  private CobolFileKey[]	k_POLICY_MASTER = null;
  private CobolFile		h_POLICY_MASTER = null;
  private byte[]	h_POLICY_MASTER_status = new byte[4];
  /* File CUSTOMER-MASTER */
  private CobolFileKey[]	k_CUSTOMER_MASTER = null;
  private CobolFile		h_CUSTOMER_MASTER = null;
  private byte[]	h_CUSTOMER_MASTER_status = new byte[4];

  /* Sections and Labels */
  private final static int l_CCLOAD01 = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN_SECTION = 3;
  private final static int l_MAIN_SECTION__LOAD_CUSTOMERS = 4;
  private final static int l_MAIN_SECTION__LOAD_POLICIES = 5;
  private final static int l_Default_Error_Handler = 6;

}
