/* Generated by opensource COBOL 4J 2.0.0 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import jp.osscons.opensourcecobol.libcobj.sql.*;
import java.util.Optional;

public class CCMAIN01 implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return CCMAIN01_(0, argStorages);
  }

  @Override
  public void cancel() {
    CCMAIN01_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int CCMAIN01_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("CCMAIN01");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("CCMAIN01");

      b_RETURN_CODE.set((int)0);
      b_WS_RC.fillBytes (48, 2);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_CCMAIN01);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_CCMAIN01]);
      }
    },
    /* Entry CCMAIN01 */
    new CobolControl(l_CCMAIN01, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN_SECTION]);
      }
    },
    /* MAIN-SECTION */
    new CobolControl(l_MAIN_SECTION__MAIN_SECTION, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCMAIN01.cob:8: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, c_1_CLAIMSCORE);
        }
        /* src/CCMAIN01.cob:9: CALL */
        {
          CobolModule.getCurrentModule ().setParameters ();
          CobolCallParams.callParams = 0;
          call_CCLOAD01 = CobolResolve.resolve(null, "CCLOAD01", call_CCLOAD01);
          b_RETURN_CODE.set (call_CCLOAD01.run ());
          f_WS_RC.setInt (b_RETURN_CODE.intValue());
        }
        /* src/CCMAIN01.cob:10: IF */
        {
          if (((long)b_WS_RC.cmpNumdisp (2, 0) != 0L))
            {
              /* src/CCMAIN01.cob:10: MOVE */
              {
                b_RETURN_CODE.set((int)12);
              }
              /* src/CCMAIN01.cob:10: GOBACK */
              {
                if(true) return Optional.of(contList[contList.length - 1]);
              }
            }
        }
        /* src/CCMAIN01.cob:11: CALL */
        {
          CobolModule.getCurrentModule ().setParameters ();
          CobolCallParams.callParams = 0;
          call_CCPROC01 = CobolResolve.resolve(null, "CCPROC01", call_CCPROC01);
          b_RETURN_CODE.set (call_CCPROC01.run ());
          f_WS_RC.setInt (b_RETURN_CODE.intValue());
        }
        /* src/CCMAIN01.cob:12: IF */
        {
          if (((long)b_WS_RC.cmpNumdisp (2, 0) != 0L))
            {
              /* src/CCMAIN01.cob:12: MOVE */
              {
                b_RETURN_CODE.set((int)12);
              }
              /* src/CCMAIN01.cob:12: GOBACK */
              {
                if(true) return Optional.of(contList[contList.length - 1]);
              }
            }
        }
        /* src/CCMAIN01.cob:13: CALL */
        {
          CobolModule.getCurrentModule ().setParameters ();
          CobolCallParams.callParams = 0;
          call_CCREPT01 = CobolResolve.resolve(null, "CCREPT01", call_CCREPT01);
          b_RETURN_CODE.set (call_CCREPT01.run ());
          f_WS_RC.setInt (b_RETURN_CODE.intValue());
        }
        /* src/CCMAIN01.cob:14: IF */
        {
          if (((long)b_WS_RC.cmpNumdisp (2, 0) != 0L))
            {
              /* src/CCMAIN01.cob:14: MOVE */
              {
                b_RETURN_CODE.set((int)12);
              }
              /* src/CCMAIN01.cob:14: GOBACK */
              {
                if(true) return Optional.of(contList[contList.length - 1]);
              }
            }
        }
        /* src/CCMAIN01.cob:15: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, c_2_CLAIMSCORE);
        }
        /* src/CCMAIN01.cob:16: MOVE */
        {
          b_RETURN_CODE.set((int)0);
        }
        /* src/CCMAIN01.cob:17: GOBACK */
        {
          if(true) return Optional.of(contList[contList.length - 1]);
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new CCMAIN01().CCMAIN01_(0);
    CobolStopRunException.stopRun();
  }

  public CCMAIN01()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : CCMAIN01 */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_WS_RC = new CobolDataStorage(2);	/* WS-RC */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : CCMAIN01 */
    f_WS_RC	= CobolFieldFactory.makeCobolField(2, b_WS_RC, a_1_NumericDisplay_Digits2_Scale0);	/* WS-RC */

    /* End of fields */


    /* Constants */

    c_1_CLAIMSCORE	= CobolFieldFactory.makeCobolField(str_0_CLAIMSCORE, a_2_Alphanumeric);
    c_2_CLAIMSCORE	= CobolFieldFactory.makeCobolField(str_1_CLAIMSCORE, a_2_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericDisplay_Digits2_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 2,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : CCMAIN01 */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_WS_RC;	/* WS-RC */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : CCMAIN01 */
  private AbstractCobolField f_WS_RC;	/* WS-RC */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_2_CLAIMSCORE;
  private AbstractCobolField c_1_CLAIMSCORE;

  /* Attributes */

  private CobolFieldAttribute a_2_Alphanumeric;
  private CobolFieldAttribute a_1_NumericDisplay_Digits2_Scale0;



  /* String literals */
  public static final byte[] str_1_CLAIMSCORE = CobolUtil.stringToBytes("CLAIMSCORE NIGHTLY BATCH COMPLETED");
  public static final byte[] str_0_CLAIMSCORE = CobolUtil.stringToBytes("CLAIMSCORE ENTERPRISE NIGHTLY BATCH");

  /* Sections and Labels */
  private final static int l_CCMAIN01 = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN_SECTION = 3;
  private final static int l_Default_Error_Handler = 4;

  private CobolRunnable call_CCREPT01 = null;
  private CobolRunnable call_CCPROC01 = null;
  private CobolRunnable call_CCLOAD01 = null;
}
