/* Generated by opensource COBOL 4J 2.0.0 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import jp.osscons.opensourcecobol.libcobj.sql.*;
import java.util.Optional;

public class CCPROC01 implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return CCPROC01_(0, argStorages);
  }

  @Override
  public void cancel() {
    CCPROC01_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int CCPROC01_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	h_CLAIM_IN.close (0, null);
    	h_POLICY_MASTER.close (0, null);
    	h_AUDIT_OUT.close (0, null);
    	h_EXCEPTION_OUT.close (0, null);
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("CCPROC01");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("CCPROC01");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_CLM_ID__CLAIM_RECORD.fillBytes(' ', 12);
      b_CLM_DATE__CLAIM_RECORD.fillBytes('0', 14);
      b_CLM_POLICY_ID__CLAIM_RECORD.fillBytes(' ', 14);
      b_CLM_LOSS_AMOUNT__CLAIM_RECORD.fillBytes('0', 11);
      b_CLM_DESCRIPTION__CLAIM_RECORD.fillBytes(' ', 70);
      b_WS_IN_STATUS.fillBytes(' ', 2);
      b_WS_POL_STATUS.fillBytes(' ', 2);
      b_WS_EOF.setByte(0, 'N');      b_WS_RESULT.setByte(' ');
      b_WS_ERROR_CODE.fillBytes(' ', 4);
      b_WS_ERROR_TEXT.fillBytes(' ', 80);
      f_WS_APPROVED_AMOUNT.setZero ();
      b_WS_CLAIM_COUNT.fillBytes (48, 7);
      b_WS_APPROVED_COUNT.fillBytes (48, 7);
      b_WS_REJECTED_COUNT.fillBytes (48, 7);
      b_WS_REVIEW_COUNT.fillBytes (48, 7);
      b_WS_RAW.fillBytes(' ', 152);

      h_CLAIM_IN = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "CLAIM-IN",
      /* file_status = */ h_CLAIM_IN_status,
      /* assign = */ c_1_data,
      /* record = */ f_CLAIM_IN_record,
      /* record_size = */ null,
      /* record_min = */ 0,
      /* record_max = */ 152,
      /* nkeys = */ 0,
      /* keys = */ null,
      /* organization = */ (char)1,
      /* access_mode = */ (char)1,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)0,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)1,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );
      if (k_POLICY_MASTER == null)
      {
        k_POLICY_MASTER = new CobolFileKey[1];
        for (int i=0; i<1; ++i)
          k_POLICY_MASTER[i] = new CobolFileKey();
      }
      k_POLICY_MASTER[0].setField(f_POL_POLICY_ID__POLICY_RECORD);
      k_POLICY_MASTER[0].setFlag(0);
      k_POLICY_MASTER[0].setOffset(0);
      h_POLICY_MASTER = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "POLICY-MASTER",
      /* file_status = */ h_POLICY_MASTER_status,
      /* assign = */ c_2_data,
      /* record = */ f_POLICY_MASTER_record,
      /* record_size = */ null,
      /* record_min = */ 71,
      /* record_max = */ 71,
      /* nkeys = */ 1,
      /* keys = */ k_POLICY_MASTER,
      /* organization = */ (char)3,
      /* access_mode = */ (char)2,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)0,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)1,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );
      h_AUDIT_OUT = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "AUDIT-OUT",
      /* file_status = */ h_AUDIT_OUT_status,
      /* assign = */ c_3_data,
      /* record = */ f_AUDIT_OUT_record,
      /* record_size = */ null,
      /* record_min = */ 0,
      /* record_max = */ 220,
      /* nkeys = */ 0,
      /* keys = */ null,
      /* organization = */ (char)1,
      /* access_mode = */ (char)1,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)0,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)0,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );
      h_EXCEPTION_OUT = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "EXCEPTION-OUT",
      /* file_status = */ h_EXCEPTION_OUT_status,
      /* assign = */ c_4_data,
      /* record = */ f_EXCEPTION_OUT_record,
      /* record_size = */ null,
      /* record_min = */ 0,
      /* record_max = */ 220,
      /* nkeys = */ 0,
      /* keys = */ null,
      /* organization = */ (char)1,
      /* access_mode = */ (char)1,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)0,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)0,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );

      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_CCPROC01);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_CCPROC01]);
      }
    },
    /* Entry CCPROC01 */
    new CobolControl(l_CCPROC01, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN_SECTION]);
      }
    },
    /* MAIN-SECTION */
    new CobolControl(l_MAIN_SECTION__MAIN_SECTION, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCPROC01.cob:52: OPEN */
        {
          CobolRuntimeException.code = 0;
          {
            h_CLAIM_IN.open (1, 0, f_WS_IN_STATUS);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* src/CCPROC01.cob:53: OPEN */
        {
          CobolRuntimeException.code = 0;
          {
            h_POLICY_MASTER.open (3, 1, f_WS_POL_STATUS);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* src/CCPROC01.cob:54: OPEN */
        {
          CobolRuntimeException.code = 0;
          {
            h_AUDIT_OUT.open (2, 1, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
          CobolRuntimeException.code = 0;
          {
            h_EXCEPTION_OUT.open (2, 1, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* src/CCPROC01.cob:55: PERFORM */
        for (;;)
        {
          if (((long)(Byte.toUnsignedInt(b_WS_EOF.getByte(0)) - (int)89) == 0L))
            break;
          {
            /* src/CCPROC01.cob:56: READ */
            CobolRuntimeException.code = 0;
            {
              h_CLAIM_IN.read (0, f_WS_IN_STATUS, 1);
            }
            if (CobolRuntimeException.code != 0)
            {
              if (CobolRuntimeException.code == 0x0501)
              {
                {
                  /* src/CCPROC01.cob:57: MOVE */
                  {
                    b_WS_EOF.setByte(89);
                  }
                }
              }
              else
              {
                /* PERFORM Default Error Handler */
                CobolControl.perform(contList, l_Default_Error_Handler).run();
              }
            }
            else
            {
              {
                /* src/CCPROC01.cob:58: PERFORM */
                /* PERFORM MAP-CLAIM */
                CobolControl.perform(contList, l_MAIN_SECTION__MAP_CLAIM).run();
                /* src/CCPROC01.cob:58: PERFORM */
                /* PERFORM PROCESS-CLAIM */
                CobolControl.perform(contList, l_MAIN_SECTION__PROCESS_CLAIM).run();
              }
            }
          }
        }
        /* src/CCPROC01.cob:61: CLOSE */
        {
          CobolRuntimeException.code = 0;
          {
            h_CLAIM_IN.close (0, f_WS_IN_STATUS);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
          CobolRuntimeException.code = 0;
          {
            h_POLICY_MASTER.close (0, f_WS_POL_STATUS);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
          CobolRuntimeException.code = 0;
          {
            h_AUDIT_OUT.close (0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
          CobolRuntimeException.code = 0;
          {
            h_EXCEPTION_OUT.close (0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* src/CCPROC01.cob:62: DISPLAY */
        {
          CobolTerminal.display (0, 1, 2, c_5_CLAIMS, f_WS_CLAIM_COUNT);
        }
        /* src/CCPROC01.cob:63: MOVE */
        {
          b_RETURN_CODE.set((int)0);
        }
        /* src/CCPROC01.cob:63: GOBACK */
        {
          if(true) return Optional.of(contList[contList.length - 1]);
        }

        return Optional.of(contList[l_MAIN_SECTION__MAP_CLAIM]);
      }
    },
    /* MAP-CLAIM */
    new CobolControl(l_MAIN_SECTION__MAP_CLAIM, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCPROC01.cob:65: MOVE */
        {
          b_WS_RAW.setBytes (b_CLAIM_LINE, 152);
        }
        /* src/CCPROC01.cob:66: MOVE */
        {
          b_CLM_ID__CLAIM_RECORD.setBytes (b_RAW_ID__WS_RAW, 12);
        }
        /* src/CCPROC01.cob:67: MOVE */
        {
          f_CLM_DATE__CLAIM_RECORD.moveFrom (f_RAW_DATE__WS_RAW);
        }
        /* src/CCPROC01.cob:68: MOVE */
        {
          f_CLM_TIME__CLAIM_RECORD.moveFrom (f_RAW_TIME__WS_RAW);
        }
        /* src/CCPROC01.cob:69: MOVE */
        {
          b_CLM_POLICY_ID__CLAIM_RECORD.setBytes (b_RAW_POLICY__WS_RAW, 10);
        }
        /* src/CCPROC01.cob:70: MOVE */
        {
          b_CLM_TYPE__CLAIM_RECORD.setBytes (b_RAW_TYPE__WS_RAW, 2);
        }
        /* src/CCPROC01.cob:71: MOVE */
        {
          b_CLM_CHANNEL__CLAIM_RECORD.setBytes (b_RAW_CHANNEL__WS_RAW, 2);
        }
        /* src/CCPROC01.cob:72: MOVE */
        {
          f_CLM_LOSS_AMOUNT__CLAIM_RECORD.moveFrom (f_RAW_AMOUNT__WS_RAW);
        }
        /* src/CCPROC01.cob:73: MOVE */
        {
          b_CLM_DESCRIPTION__CLAIM_RECORD.setBytes (b_RAW_DESC__WS_RAW, 40);
        }
        /* src/CCPROC01.cob:74: MOVE */
        {
          b_CLM_REPORTED_BY__CLAIM_RECORD.setBytes (b_RAW_REPORTER__WS_RAW, 20);
        }
        /* src/CCPROC01.cob:75: ADD */
        {
          f_WS_CLAIM_COUNT.add (c_6_1, 4);
        }

        return Optional.of(contList[l_MAIN_SECTION__PROCESS_CLAIM]);
      }
    },
    /* PROCESS-CLAIM */
    new CobolControl(l_MAIN_SECTION__PROCESS_CLAIM, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCPROC01.cob:77: MOVE */
        {
          b_WS_RESULT.setByte(86);
        }
        /* src/CCPROC01.cob:78: MOVE */
        {
          b_WS_ERROR_CODE.fillBytes (32, 4);
          b_WS_ERROR_TEXT.fillBytes (32, 80);
        }
        /* src/CCPROC01.cob:79: MOVE */
        {
          b_POL_POLICY_ID__POLICY_RECORD.setBytes (b_CLM_POLICY_ID__CLAIM_RECORD, 10);
        }
        /* src/CCPROC01.cob:80: READ */
        CobolRuntimeException.code = 0;
        {
          h_POLICY_MASTER.read (f_POL_POLICY_ID__POLICY_RECORD, f_WS_POL_STATUS, 0);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }
        /* src/CCPROC01.cob:81: IF */
        {
          if (((long)b_WS_POL_STATUS.memcmp (str_0_00, 2) != 0L))
            {
              /* src/CCPROC01.cob:82: MOVE */
              {
                b_WS_RESULT.setByte(73);
              }
              /* src/CCPROC01.cob:83: MOVE */
              {
                b_WS_ERROR_CODE.setBytes (str_1_P001, 4);
              }
              /* src/CCPROC01.cob:84: MOVE */
              {
                f_WS_ERROR_TEXT.moveFrom (c_7_POLICY);
              }
            }
          else
            {
              /* src/CCPROC01.cob:86: PERFORM */
              /* PERFORM VALIDATE-POLICY */
              CobolControl.perform(contList, l_MAIN_SECTION__VALIDATE_POLICY).run();
            }
        }
        /* src/CCPROC01.cob:88: IF */
        {
          if (((long)(Byte.toUnsignedInt(b_WS_RESULT.getByte(0)) - (int)86) == 0L))
            {
              /* src/CCPROC01.cob:88: PERFORM */
              /* PERFORM CALCULATE-SETTLEMENT */
              CobolControl.perform(contList, l_MAIN_SECTION__CALCULATE_SETTLEMENT).run();
            }
        }
        /* src/CCPROC01.cob:89: IF */
        {
          if ((((long)(Byte.toUnsignedInt(b_WS_RESULT.getByte(0)) - (int)86) == 0L) || ((long)(Byte.toUnsignedInt(b_WS_RESULT.getByte(0)) - (int)77) == 0L)))
            {
              /* src/CCPROC01.cob:90: PERFORM */
              /* PERFORM WRITE-AUDIT */
              CobolControl.perform(contList, l_MAIN_SECTION__WRITE_AUDIT).run();
            }
          else
            {
              /* src/CCPROC01.cob:92: PERFORM */
              /* PERFORM WRITE-REJECTION */
              CobolControl.perform(contList, l_MAIN_SECTION__WRITE_REJECTION).run();
            }
        }

        return Optional.of(contList[l_MAIN_SECTION__VALIDATE_POLICY]);
      }
    },
    /* VALIDATE-POLICY */
    new CobolControl(l_MAIN_SECTION__VALIDATE_POLICY, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCPROC01.cob:95: EVALUATE */
        {
          if (((long)(Byte.toUnsignedInt(b_POL_STATUS__POLICY_RECORD.getByte(0)) - (int)65) != 0L))
            {
              /* src/CCPROC01.cob:97: MOVE */
              {
                b_WS_RESULT.setByte(73);
              }
              /* src/CCPROC01.cob:98: MOVE */
              {
                b_WS_ERROR_CODE.setBytes (str_2_P002, 4);
              }
              /* src/CCPROC01.cob:99: MOVE */
              {
                f_WS_ERROR_TEXT.moveFrom (c_8_POLICY);
              }
            }
          else
            if (((long)b_CLM_TYPE__CLAIM_RECORD.memcmp (b_POL_TYPE__POLICY_RECORD, 2) != 0L))
              {
                /* src/CCPROC01.cob:101: MOVE */
                {
                  b_WS_RESULT.setByte(73);
                }
                /* src/CCPROC01.cob:102: MOVE */
                {
                  b_WS_ERROR_CODE.setBytes (str_3_P003, 4);
                }
                /* src/CCPROC01.cob:103: MOVE */
                {
                  f_WS_ERROR_TEXT.moveFrom (c_9_CLAIM);
                }
              }
            else
              {
                /* src/CCPROC01.cob:104: CONTINUE */
                {
                  ;
                }
              }
        }

        return Optional.of(contList[l_MAIN_SECTION__CALCULATE_SETTLEMENT]);
      }
    },
    /* CALCULATE-SETTLEMENT */
    new CobolControl(l_MAIN_SECTION__CALCULATE_SETTLEMENT, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCPROC01.cob:107: COMPUTE */
        {
          {
            {
              d0.setField (f_CLM_LOSS_AMOUNT__CLAIM_RECORD);
              d1.setField (f_POL_DEDUCTIBLE__POLICY_RECORD);
              d0.sub (d1);
              d0.getField (f_WS_APPROVED_AMOUNT, 4);
            }
          }
        }
        /* src/CCPROC01.cob:108: IF */
        {
          if (((long)f_WS_APPROVED_AMOUNT.cmpInteger (0) <  0L))
            {
              /* src/CCPROC01.cob:108: MOVE */
              {
                f_WS_APPROVED_AMOUNT.setZero ();
              }
            }
        }
        /* src/CCPROC01.cob:109: IF */
        {
          if (((long)f_WS_APPROVED_AMOUNT.compareTo (f_POL_COVER_LIMIT__POLICY_RECORD) >  0L))
            {
              /* src/CCPROC01.cob:110: MOVE */
              {
                b_WS_APPROVED_AMOUNT.setBytes (b_POL_COVER_LIMIT__POLICY_RECORD, 7);
              }
            }
        }
        /* src/CCPROC01.cob:112: IF */
        {
          if (((long)f_WS_APPROVED_AMOUNT.cmpInteger (200000) >  0L))
            {
              /* src/CCPROC01.cob:112: MOVE */
              {
                b_WS_RESULT.setByte(77);
              }
            }
        }

        return Optional.of(contList[l_MAIN_SECTION__WRITE_AUDIT]);
      }
    },
    /* WRITE-AUDIT */
    new CobolControl(l_MAIN_SECTION__WRITE_AUDIT, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCPROC01.cob:114: IF */
        {
          if (((long)(Byte.toUnsignedInt(b_WS_RESULT.getByte(0)) - (int)77) == 0L))
            {
              /* src/CCPROC01.cob:115: STRING */
              {
                CobolString.stringInit (f_AUDIT_LINE, 0);
                CobolString.stringDelimited (0);
                CobolString.stringAppend (f_CLM_ID__CLAIM_RECORD);
                CobolString.stringAppend (c_10);
                CobolString.stringAppend (f_CLM_POLICY_ID__CLAIM_RECORD);
                CobolString.stringAppend (c_11);
                CobolString.stringAppend (f_WS_APPROVED_AMOUNT);
                CobolString.stringAppend (c_10);
                CobolString.stringAppend (f_CLM_DESCRIPTION__CLAIM_RECORD);
                CobolString.stringFinish ();
              }
              /* src/CCPROC01.cob:117: WRITE */
              CobolRuntimeException.code = 0;
              {
                h_AUDIT_OUT.write (f_AUDIT_LINE, 2162689, null);
              }
              if (CobolRuntimeException.code != 0)
              {
                /* PERFORM Default Error Handler */
                CobolControl.perform(contList, l_Default_Error_Handler).run();
              }
              /* src/CCPROC01.cob:118: ADD */
              {
                f_WS_REVIEW_COUNT.add (c_6_1, 4);
              }
            }
          else
            {
              /* src/CCPROC01.cob:120: STRING */
              {
                CobolString.stringInit (f_AUDIT_LINE, 0);
                CobolString.stringDelimited (0);
                CobolString.stringAppend (f_CLM_ID__CLAIM_RECORD);
                CobolString.stringAppend (c_10);
                CobolString.stringAppend (f_CLM_POLICY_ID__CLAIM_RECORD);
                CobolString.stringAppend (c_12);
                CobolString.stringAppend (f_WS_APPROVED_AMOUNT);
                CobolString.stringAppend (c_10);
                CobolString.stringAppend (f_CLM_DESCRIPTION__CLAIM_RECORD);
                CobolString.stringFinish ();
              }
              /* src/CCPROC01.cob:122: WRITE */
              CobolRuntimeException.code = 0;
              {
                h_AUDIT_OUT.write (f_AUDIT_LINE, 2162689, null);
              }
              if (CobolRuntimeException.code != 0)
              {
                /* PERFORM Default Error Handler */
                CobolControl.perform(contList, l_Default_Error_Handler).run();
              }
              /* src/CCPROC01.cob:123: ADD */
              {
                f_WS_APPROVED_COUNT.add (c_6_1, 4);
              }
            }
        }

        return Optional.of(contList[l_MAIN_SECTION__WRITE_REJECTION]);
      }
    },
    /* WRITE-REJECTION */
    new CobolControl(l_MAIN_SECTION__WRITE_REJECTION, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCPROC01.cob:126: ADD */
        {
          f_WS_REJECTED_COUNT.add (c_6_1, 4);
        }
        /* src/CCPROC01.cob:127: STRING */
        {
          CobolString.stringInit (f_EXCEPTION_LINE, 0);
          CobolString.stringDelimited (0);
          CobolString.stringAppend (f_CLM_ID__CLAIM_RECORD);
          CobolString.stringAppend (c_10);
          CobolString.stringAppend (f_CLM_POLICY_ID__CLAIM_RECORD);
          CobolString.stringAppend (c_10);
          CobolString.stringAppend (f_WS_ERROR_CODE);
          CobolString.stringAppend (c_10);
          CobolString.stringAppend (f_WS_ERROR_TEXT);
          CobolString.stringAppend (c_10);
          CobolString.stringAppend (f_CLM_DESCRIPTION__CLAIM_RECORD);
          CobolString.stringFinish ();
        }
        /* src/CCPROC01.cob:129: WRITE */
        CobolRuntimeException.code = 0;
        {
          h_EXCEPTION_OUT.write (f_EXCEPTION_LINE, 2162689, null);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }


        return Optional.of(CobolControl.pure());
      }
    },
    /* Default Error Handler */
    new CobolControl(l_Default_Error_Handler, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        if ((CobolFile.errorFile.flag_select_features & CobolFile.COB_SELECT_FILE_STATUS) == 0) {
        	CobolFile.defaultErrorHandle ();
        	CobolStopRunException.stopRunAndThrow (1);
        }

        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new CCPROC01().CCPROC01_(0);
    CobolStopRunException.stopRun();
  }

  public CCPROC01()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : CCPROC01 */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_CLAIM_IN_record = new CobolDataStorage(152);	/* CLAIM-IN_record */
    b_POLICY_MASTER_record = new CobolDataStorage(71);	/* POLICY-MASTER_record */
    b_AUDIT_OUT_record = new CobolDataStorage(220);	/* AUDIT-OUT_record */
    b_EXCEPTION_OUT_record = new CobolDataStorage(220);	/* EXCEPTION-OUT_record */
    b_CLAIM_RECORD = new CobolDataStorage(121);	/* CLAIM-RECORD */
    b_WS_IN_STATUS = new CobolDataStorage(2);	/* WS-IN-STATUS */
    b_WS_POL_STATUS = new CobolDataStorage(2);	/* WS-POL-STATUS */
    b_WS_EOF = new CobolDataStorage(1);	/* WS-EOF */
    b_WS_RESULT = new CobolDataStorage(1);	/* WS-RESULT */
    b_WS_ERROR_CODE = new CobolDataStorage(4);	/* WS-ERROR-CODE */
    b_WS_ERROR_TEXT = new CobolDataStorage(80);	/* WS-ERROR-TEXT */
    b_WS_APPROVED_AMOUNT = new CobolDataStorage(7);	/* WS-APPROVED-AMOUNT */
    b_WS_CLAIM_COUNT = new CobolDataStorage(7);	/* WS-CLAIM-COUNT */
    b_WS_APPROVED_COUNT = new CobolDataStorage(7);	/* WS-APPROVED-COUNT */
    b_WS_REJECTED_COUNT = new CobolDataStorage(7);	/* WS-REJECTED-COUNT */
    b_WS_REVIEW_COUNT = new CobolDataStorage(7);	/* WS-REVIEW-COUNT */
    b_WS_RAW = new CobolDataStorage(152);	/* WS-RAW */
    b_AUDIT_LINE = b_AUDIT_OUT_record;
    b_CLAIM_LINE = b_CLAIM_IN_record;
    b_CLM_CHANNEL__CLAIM_RECORD = b_CLAIM_RECORD.getSubDataStorage(38);
    b_CLM_DATE__CLAIM_RECORD = b_CLAIM_RECORD.getSubDataStorage(12);
    b_CLM_DESCRIPTION__CLAIM_RECORD = b_CLAIM_RECORD.getSubDataStorage(51);
    b_CLM_ID__CLAIM_RECORD = b_CLAIM_RECORD;
    b_CLM_LOSS_AMOUNT__CLAIM_RECORD = b_CLAIM_RECORD.getSubDataStorage(40);
    b_CLM_POLICY_ID__CLAIM_RECORD = b_CLAIM_RECORD.getSubDataStorage(26);
    b_CLM_REPORTED_BY__CLAIM_RECORD = b_CLAIM_RECORD.getSubDataStorage(91);
    b_CLM_TIME__CLAIM_RECORD = b_CLAIM_RECORD.getSubDataStorage(20);
    b_CLM_TYPE__CLAIM_RECORD = b_CLAIM_RECORD.getSubDataStorage(36);
    b_EXCEPTION_LINE = b_EXCEPTION_OUT_record;
    b_POL_COVER_LIMIT__POLICY_RECORD = b_POLICY_MASTER_record.getSubDataStorage(22);
    b_POL_DEDUCTIBLE__POLICY_RECORD = b_POLICY_MASTER_record.getSubDataStorage(29);
    b_POL_POLICY_ID__POLICY_RECORD = b_POLICY_MASTER_record;
    b_POL_STATUS__POLICY_RECORD = b_POLICY_MASTER_record.getSubDataStorage(18);
    b_POL_TYPE__POLICY_RECORD = b_POLICY_MASTER_record.getSubDataStorage(16);
    b_RAW_AMOUNT__WS_RAW = b_WS_RAW.getSubDataStorage(40);
    b_RAW_CHANNEL__WS_RAW = b_WS_RAW.getSubDataStorage(38);
    b_RAW_DATE__WS_RAW = b_WS_RAW.getSubDataStorage(12);
    b_RAW_DESC__WS_RAW = b_WS_RAW.getSubDataStorage(52);
    b_RAW_ID__WS_RAW = b_WS_RAW;
    b_RAW_POLICY__WS_RAW = b_WS_RAW.getSubDataStorage(26);
    b_RAW_REPORTER__WS_RAW = b_WS_RAW.getSubDataStorage(92);
    b_RAW_TIME__WS_RAW = b_WS_RAW.getSubDataStorage(20);
    b_RAW_TYPE__WS_RAW = b_WS_RAW.getSubDataStorage(36);

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : CCPROC01 */
    f_CLAIM_IN_record	= CobolFieldFactory.makeCobolField(152, b_CLAIM_IN_record, a_2_Alphanumeric);	/* CLAIM-IN_record */
    f_POL_POLICY_ID__POLICY_RECORD	= CobolFieldFactory.makeCobolField(10, b_POL_POLICY_ID__POLICY_RECORD, a_2_Alphanumeric);	/* POL-POLICY-ID */
    f_POL_COVER_LIMIT__POLICY_RECORD	= CobolFieldFactory.makeCobolField(7, b_POL_COVER_LIMIT__POLICY_RECORD, a_1_NumericPacked_Digits13_Scale2_HaveSign);	/* POL-COVER-LIMIT */
    f_POL_DEDUCTIBLE__POLICY_RECORD	= CobolFieldFactory.makeCobolField(6, b_POL_DEDUCTIBLE__POLICY_RECORD, a_7_NumericPacked_Digits11_Scale2_HaveSign);	/* POL-DEDUCTIBLE */
    f_POLICY_MASTER_record	= CobolFieldFactory.makeCobolField(71, b_POLICY_MASTER_record, a_2_Alphanumeric);	/* POLICY-MASTER_record */
    f_AUDIT_LINE	= CobolFieldFactory.makeCobolField(220, b_AUDIT_LINE, a_2_Alphanumeric);	/* AUDIT-LINE */
    f_AUDIT_OUT_record	= CobolFieldFactory.makeCobolField(220, b_AUDIT_OUT_record, a_2_Alphanumeric);	/* AUDIT-OUT_record */
    f_EXCEPTION_LINE	= CobolFieldFactory.makeCobolField(220, b_EXCEPTION_LINE, a_2_Alphanumeric);	/* EXCEPTION-LINE */
    f_EXCEPTION_OUT_record	= CobolFieldFactory.makeCobolField(220, b_EXCEPTION_OUT_record, a_2_Alphanumeric);	/* EXCEPTION-OUT_record */
    f_CLM_ID__CLAIM_RECORD	= CobolFieldFactory.makeCobolField(12, b_CLM_ID__CLAIM_RECORD, a_2_Alphanumeric);	/* CLM-ID */
    f_CLM_DATE__CLAIM_RECORD	= CobolFieldFactory.makeCobolField(8, b_CLM_DATE__CLAIM_RECORD, a_4_NumericDisplay_Digits8_Scale0);	/* CLM-DATE */
    f_CLM_TIME__CLAIM_RECORD	= CobolFieldFactory.makeCobolField(6, b_CLM_TIME__CLAIM_RECORD, a_5_NumericDisplay_Digits6_Scale0);	/* CLM-TIME */
    f_CLM_POLICY_ID__CLAIM_RECORD	= CobolFieldFactory.makeCobolField(10, b_CLM_POLICY_ID__CLAIM_RECORD, a_2_Alphanumeric);	/* CLM-POLICY-ID */
    f_CLM_LOSS_AMOUNT__CLAIM_RECORD	= CobolFieldFactory.makeCobolField(11, b_CLM_LOSS_AMOUNT__CLAIM_RECORD, a_6_NumericDisplay_Digits11_Scale2);	/* CLM-LOSS-AMOUNT */
    f_CLM_DESCRIPTION__CLAIM_RECORD	= CobolFieldFactory.makeCobolField(40, b_CLM_DESCRIPTION__CLAIM_RECORD, a_2_Alphanumeric);	/* CLM-DESCRIPTION */
    f_WS_IN_STATUS	= CobolFieldFactory.makeCobolField(2, b_WS_IN_STATUS, a_2_Alphanumeric);	/* WS-IN-STATUS */
    f_WS_POL_STATUS	= CobolFieldFactory.makeCobolField(2, b_WS_POL_STATUS, a_2_Alphanumeric);	/* WS-POL-STATUS */
    f_WS_ERROR_CODE	= CobolFieldFactory.makeCobolField(4, b_WS_ERROR_CODE, a_2_Alphanumeric);	/* WS-ERROR-CODE */
    f_WS_ERROR_TEXT	= CobolFieldFactory.makeCobolField(80, b_WS_ERROR_TEXT, a_2_Alphanumeric);	/* WS-ERROR-TEXT */
    f_WS_APPROVED_AMOUNT	= CobolFieldFactory.makeCobolField(7, b_WS_APPROVED_AMOUNT, a_1_NumericPacked_Digits13_Scale2_HaveSign);	/* WS-APPROVED-AMOUNT */
    f_WS_CLAIM_COUNT	= CobolFieldFactory.makeCobolField(7, b_WS_CLAIM_COUNT, a_3_NumericDisplay_Digits7_Scale0);	/* WS-CLAIM-COUNT */
    f_WS_APPROVED_COUNT	= CobolFieldFactory.makeCobolField(7, b_WS_APPROVED_COUNT, a_3_NumericDisplay_Digits7_Scale0);	/* WS-APPROVED-COUNT */
    f_WS_REJECTED_COUNT	= CobolFieldFactory.makeCobolField(7, b_WS_REJECTED_COUNT, a_3_NumericDisplay_Digits7_Scale0);	/* WS-REJECTED-COUNT */
    f_WS_REVIEW_COUNT	= CobolFieldFactory.makeCobolField(7, b_WS_REVIEW_COUNT, a_3_NumericDisplay_Digits7_Scale0);	/* WS-REVIEW-COUNT */
    f_RAW_DATE__WS_RAW	= CobolFieldFactory.makeCobolField(8, b_RAW_DATE__WS_RAW, a_2_Alphanumeric);	/* RAW-DATE */
    f_RAW_TIME__WS_RAW	= CobolFieldFactory.makeCobolField(6, b_RAW_TIME__WS_RAW, a_2_Alphanumeric);	/* RAW-TIME */
    f_RAW_AMOUNT__WS_RAW	= CobolFieldFactory.makeCobolField(12, b_RAW_AMOUNT__WS_RAW, a_2_Alphanumeric);	/* RAW-AMOUNT */

    /* End of fields */


    /* Constants */

    c_1_data	= CobolFieldFactory.makeCobolField(str_4_data, a_2_Alphanumeric);
    c_2_data	= CobolFieldFactory.makeCobolField(str_5_data, a_2_Alphanumeric);
    c_3_data	= CobolFieldFactory.makeCobolField(str_6_data, a_2_Alphanumeric);
    c_4_data	= CobolFieldFactory.makeCobolField(str_7_data, a_2_Alphanumeric);
    c_5_CLAIMS	= CobolFieldFactory.makeCobolField(str_8_CLAIMS, a_2_Alphanumeric);
    c_6_1	= CobolFieldFactory.makeCobolField(1, "1", a_8_NumericDisplay_Digits1_Scale0);
    c_7_POLICY	= CobolFieldFactory.makeCobolField(str_9_POLICY, a_2_Alphanumeric);
    c_8_POLICY	= CobolFieldFactory.makeCobolField(str_10_POLICY, a_2_Alphanumeric);
    c_9_CLAIM	= CobolFieldFactory.makeCobolField(str_11_CLAIM, a_2_Alphanumeric);
    c_10	= CobolFieldFactory.makeCobolField(str_12, a_2_Alphanumeric);
    c_11	= CobolFieldFactory.makeCobolField(str_13, a_2_Alphanumeric);
    c_12	= CobolFieldFactory.makeCobolField(str_14, a_2_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericPacked_Digits13_Scale2_HaveSign = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_PACKED,
      /* digits= */ 13,
      /* scale= */ 2,
      CobolFieldAttribute.COB_FLAG_HAVE_SIGN,
      /* pic= */ null);
    a_2_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits7_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 7,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_4_NumericDisplay_Digits8_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 8,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_5_NumericDisplay_Digits6_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 6,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_6_NumericDisplay_Digits11_Scale2 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 11,
      /* scale= */ 2,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_7_NumericPacked_Digits11_Scale2_HaveSign = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_PACKED,
      /* digits= */ 11,
      /* scale= */ 2,
      CobolFieldAttribute.COB_FLAG_HAVE_SIGN,
      /* pic= */ null);
    a_8_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;

  /* Data storage */

  /* PROGRAM-ID : CCPROC01 */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_CLAIM_IN_record;	/* CLAIM-IN_record */
  private CobolDataStorage b_POLICY_MASTER_record;	/* POLICY-MASTER_record */
  private CobolDataStorage b_AUDIT_OUT_record;	/* AUDIT-OUT_record */
  private CobolDataStorage b_EXCEPTION_OUT_record;	/* EXCEPTION-OUT_record */
  private CobolDataStorage b_CLAIM_RECORD;	/* CLAIM-RECORD */
  private CobolDataStorage b_WS_IN_STATUS;	/* WS-IN-STATUS */
  private CobolDataStorage b_WS_POL_STATUS;	/* WS-POL-STATUS */
  private CobolDataStorage b_WS_EOF;	/* WS-EOF */
  private CobolDataStorage b_WS_RESULT;	/* WS-RESULT */
  private CobolDataStorage b_WS_ERROR_CODE;	/* WS-ERROR-CODE */
  private CobolDataStorage b_WS_ERROR_TEXT;	/* WS-ERROR-TEXT */
  private CobolDataStorage b_WS_APPROVED_AMOUNT;	/* WS-APPROVED-AMOUNT */
  private CobolDataStorage b_WS_CLAIM_COUNT;	/* WS-CLAIM-COUNT */
  private CobolDataStorage b_WS_APPROVED_COUNT;	/* WS-APPROVED-COUNT */
  private CobolDataStorage b_WS_REJECTED_COUNT;	/* WS-REJECTED-COUNT */
  private CobolDataStorage b_WS_REVIEW_COUNT;	/* WS-REVIEW-COUNT */
  private CobolDataStorage b_WS_RAW;	/* WS-RAW */
  private CobolDataStorage b_AUDIT_LINE;
  private CobolDataStorage b_CLAIM_LINE;
  private CobolDataStorage b_CLM_CHANNEL__CLAIM_RECORD;
  private CobolDataStorage b_CLM_DATE__CLAIM_RECORD;
  private CobolDataStorage b_CLM_DESCRIPTION__CLAIM_RECORD;
  private CobolDataStorage b_CLM_ID__CLAIM_RECORD;
  private CobolDataStorage b_CLM_LOSS_AMOUNT__CLAIM_RECORD;
  private CobolDataStorage b_CLM_POLICY_ID__CLAIM_RECORD;
  private CobolDataStorage b_CLM_REPORTED_BY__CLAIM_RECORD;
  private CobolDataStorage b_CLM_TIME__CLAIM_RECORD;
  private CobolDataStorage b_CLM_TYPE__CLAIM_RECORD;
  private CobolDataStorage b_EXCEPTION_LINE;
  private CobolDataStorage b_POL_COVER_LIMIT__POLICY_RECORD;
  private CobolDataStorage b_POL_DEDUCTIBLE__POLICY_RECORD;
  private CobolDataStorage b_POL_POLICY_ID__POLICY_RECORD;
  private CobolDataStorage b_POL_STATUS__POLICY_RECORD;
  private CobolDataStorage b_POL_TYPE__POLICY_RECORD;
  private CobolDataStorage b_RAW_AMOUNT__WS_RAW;
  private CobolDataStorage b_RAW_CHANNEL__WS_RAW;
  private CobolDataStorage b_RAW_DATE__WS_RAW;
  private CobolDataStorage b_RAW_DESC__WS_RAW;
  private CobolDataStorage b_RAW_ID__WS_RAW;
  private CobolDataStorage b_RAW_POLICY__WS_RAW;
  private CobolDataStorage b_RAW_REPORTER__WS_RAW;
  private CobolDataStorage b_RAW_TIME__WS_RAW;
  private CobolDataStorage b_RAW_TYPE__WS_RAW;

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : CCPROC01 */
  private AbstractCobolField f_CLAIM_IN_record;	/* CLAIM-IN_record */
  private AbstractCobolField f_POL_POLICY_ID__POLICY_RECORD;	/* POL-POLICY-ID */
  private AbstractCobolField f_POL_COVER_LIMIT__POLICY_RECORD;	/* POL-COVER-LIMIT */
  private AbstractCobolField f_POL_DEDUCTIBLE__POLICY_RECORD;	/* POL-DEDUCTIBLE */
  private AbstractCobolField f_POLICY_MASTER_record;	/* POLICY-MASTER_record */
  private AbstractCobolField f_AUDIT_LINE;	/* AUDIT-LINE */
  private AbstractCobolField f_AUDIT_OUT_record;	/* AUDIT-OUT_record */
  private AbstractCobolField f_EXCEPTION_LINE;	/* EXCEPTION-LINE */
  private AbstractCobolField f_EXCEPTION_OUT_record;	/* EXCEPTION-OUT_record */
  private AbstractCobolField f_CLM_ID__CLAIM_RECORD;	/* CLM-ID */
  private AbstractCobolField f_CLM_DATE__CLAIM_RECORD;	/* CLM-DATE */
  private AbstractCobolField f_CLM_TIME__CLAIM_RECORD;	/* CLM-TIME */
  private AbstractCobolField f_CLM_POLICY_ID__CLAIM_RECORD;	/* CLM-POLICY-ID */
  private AbstractCobolField f_CLM_LOSS_AMOUNT__CLAIM_RECORD;	/* CLM-LOSS-AMOUNT */
  private AbstractCobolField f_CLM_DESCRIPTION__CLAIM_RECORD;	/* CLM-DESCRIPTION */
  private AbstractCobolField f_WS_IN_STATUS;	/* WS-IN-STATUS */
  private AbstractCobolField f_WS_POL_STATUS;	/* WS-POL-STATUS */
  private AbstractCobolField f_WS_ERROR_CODE;	/* WS-ERROR-CODE */
  private AbstractCobolField f_WS_ERROR_TEXT;	/* WS-ERROR-TEXT */
  private AbstractCobolField f_WS_APPROVED_AMOUNT;	/* WS-APPROVED-AMOUNT */
  private AbstractCobolField f_WS_CLAIM_COUNT;	/* WS-CLAIM-COUNT */
  private AbstractCobolField f_WS_APPROVED_COUNT;	/* WS-APPROVED-COUNT */
  private AbstractCobolField f_WS_REJECTED_COUNT;	/* WS-REJECTED-COUNT */
  private AbstractCobolField f_WS_REVIEW_COUNT;	/* WS-REVIEW-COUNT */
  private AbstractCobolField f_RAW_DATE__WS_RAW;	/* RAW-DATE */
  private AbstractCobolField f_RAW_TIME__WS_RAW;	/* RAW-TIME */
  private AbstractCobolField f_RAW_AMOUNT__WS_RAW;	/* RAW-AMOUNT */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_12;
  private AbstractCobolField c_11;
  private AbstractCobolField c_10;
  private AbstractCobolField c_9_CLAIM;
  private AbstractCobolField c_8_POLICY;
  private AbstractCobolField c_7_POLICY;
  private AbstractCobolField c_6_1;
  private AbstractCobolField c_5_CLAIMS;
  private AbstractCobolField c_4_data;
  private AbstractCobolField c_3_data;
  private AbstractCobolField c_2_data;
  private AbstractCobolField c_1_data;

  /* Attributes */

  private CobolFieldAttribute a_8_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_7_NumericPacked_Digits11_Scale2_HaveSign;
  private CobolFieldAttribute a_6_NumericDisplay_Digits11_Scale2;
  private CobolFieldAttribute a_5_NumericDisplay_Digits6_Scale0;
  private CobolFieldAttribute a_4_NumericDisplay_Digits8_Scale0;
  private CobolFieldAttribute a_3_NumericDisplay_Digits7_Scale0;
  private CobolFieldAttribute a_2_Alphanumeric;
  private CobolFieldAttribute a_1_NumericPacked_Digits13_Scale2_HaveSign;



  /* String literals */
  public static final byte[] str_14 = CobolUtil.stringToBytes("|APPROVED|");
  public static final byte[] str_13 = CobolUtil.stringToBytes("|MANUAL_REVIEW|");
  public static final byte[] str_12 = CobolUtil.stringToBytes("|");
  public static final byte[] str_11_CLAIM = CobolUtil.stringToBytes("CLAIM TYPE NOT COVERED BY POLICY");
  public static final byte[] str_10_POLICY = CobolUtil.stringToBytes("POLICY INACTIVE OR EXPIRED");
  public static final byte[] str_9_POLICY = CobolUtil.stringToBytes("POLICY NOT FOUND");
  public static final byte[] str_8_CLAIMS = CobolUtil.stringToBytes("CLAIMS PROCESSED: ");
  public static final byte[] str_7_data = CobolUtil.stringToBytes("data/out/claim-exceptions.dat");
  public static final byte[] str_6_data = CobolUtil.stringToBytes("data/out/claim-audit.dat");
  public static final byte[] str_5_data = CobolUtil.stringToBytes("data/work/policy.dat");
  public static final byte[] str_4_data = CobolUtil.stringToBytes("data/in/claims.dat");
  public static final byte[] str_3_P003 = CobolUtil.stringToBytes("P003");
  public static final byte[] str_2_P002 = CobolUtil.stringToBytes("P002");
  public static final byte[] str_1_P001 = CobolUtil.stringToBytes("P001");
  public static final byte[] str_0_00 = CobolUtil.stringToBytes("00");
  /* File CLAIM-IN */
  private CobolFile		h_CLAIM_IN = null;
  private byte[]	h_CLAIM_IN_status = new byte[4];
  /* File POLICY-MASTER */
  private CobolFileKey[]	k_POLICY_MASTER = null;
  private CobolFile		h_POLICY_MASTER = null;
  private byte[]	h_POLICY_MASTER_status = new byte[4];
  /* File AUDIT-OUT */
  private CobolFile		h_AUDIT_OUT = null;
  private byte[]	h_AUDIT_OUT_status = new byte[4];
  /* File EXCEPTION-OUT */
  private CobolFile		h_EXCEPTION_OUT = null;
  private byte[]	h_EXCEPTION_OUT_status = new byte[4];

  /* Sections and Labels */
  private final static int l_CCPROC01 = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN_SECTION = 3;
  private final static int l_MAIN_SECTION__MAP_CLAIM = 4;
  private final static int l_MAIN_SECTION__PROCESS_CLAIM = 5;
  private final static int l_MAIN_SECTION__VALIDATE_POLICY = 6;
  private final static int l_MAIN_SECTION__CALCULATE_SETTLEMENT = 7;
  private final static int l_MAIN_SECTION__WRITE_AUDIT = 8;
  private final static int l_MAIN_SECTION__WRITE_REJECTION = 9;
  private final static int l_Default_Error_Handler = 10;

}
