/* Generated by opensource COBOL 4J 2.0.0 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import jp.osscons.opensourcecobol.libcobj.sql.*;
import java.util.Optional;

public class CCREPT01 implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return CCREPT01_(0, argStorages);
  }

  @Override
  public void cancel() {
    CCREPT01_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int CCREPT01_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	h_AUDIT_IN.close (0, null);
    	h_EXCEPTION_IN.close (0, null);
    	h_REPORT_OUT.close (0, null);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("CCREPT01");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("CCREPT01");

      b_RETURN_CODE.set((int)0);
      b_WS_AUDIT_EOF.setByte(0, 'N');      b_WS_EXC_EOF.setByte(0, 'N');      b_WS_AUDIT_COUNT.fillBytes (48, 7);
      b_WS_EXCEPTION_COUNT.fillBytes (48, 7);
      b_WS_REVIEW_COUNT.fillBytes (48, 7);

      h_AUDIT_IN = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "AUDIT-IN",
      /* file_status = */ h_AUDIT_IN_status,
      /* assign = */ c_1_data,
      /* record = */ f_AUDIT_IN_record,
      /* record_size = */ null,
      /* record_min = */ 0,
      /* record_max = */ 220,
      /* nkeys = */ 0,
      /* keys = */ null,
      /* organization = */ (char)1,
      /* access_mode = */ (char)1,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)0,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)0,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );
      h_EXCEPTION_IN = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "EXCEPTION-IN",
      /* file_status = */ h_EXCEPTION_IN_status,
      /* assign = */ c_2_data,
      /* record = */ f_EXCEPTION_IN_record,
      /* record_size = */ null,
      /* record_min = */ 0,
      /* record_max = */ 220,
      /* nkeys = */ 0,
      /* keys = */ null,
      /* organization = */ (char)1,
      /* access_mode = */ (char)1,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)0,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)0,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );
      h_REPORT_OUT = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "REPORT-OUT",
      /* file_status = */ h_REPORT_OUT_status,
      /* assign = */ c_3_data,
      /* record = */ f_REPORT_OUT_record,
      /* record_size = */ null,
      /* record_min = */ 0,
      /* record_max = */ 160,
      /* nkeys = */ 0,
      /* keys = */ null,
      /* organization = */ (char)1,
      /* access_mode = */ (char)1,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)0,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)0,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );

      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_CCREPT01);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_CCREPT01]);
      }
    },
    /* Entry CCREPT01 */
    new CobolControl(l_CCREPT01, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN_SECTION]);
      }
    },
    /* MAIN-SECTION */
    new CobolControl(l_MAIN_SECTION__MAIN_SECTION, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCREPT01.cob:28: OPEN */
        {
          CobolRuntimeException.code = 0;
          {
            h_AUDIT_IN.open (1, 0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
          CobolRuntimeException.code = 0;
          {
            h_EXCEPTION_IN.open (1, 0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* src/CCREPT01.cob:29: OPEN */
        {
          CobolRuntimeException.code = 0;
          {
            h_REPORT_OUT.open (2, 1, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* src/CCREPT01.cob:30: PERFORM */
        /* PERFORM READ-AUDIT */
        CobolControl.perform(contList, l_MAIN_SECTION__READ_AUDIT).run();
        /* src/CCREPT01.cob:31: PERFORM */
        /* PERFORM READ-EXCEPTIONS */
        CobolControl.perform(contList, l_MAIN_SECTION__READ_EXCEPTIONS).run();
        /* src/CCREPT01.cob:32: PERFORM */
        /* PERFORM WRITE-REPORT */
        CobolControl.perform(contList, l_MAIN_SECTION__WRITE_REPORT).run();
        /* src/CCREPT01.cob:33: CLOSE */
        {
          CobolRuntimeException.code = 0;
          {
            h_AUDIT_IN.close (0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
          CobolRuntimeException.code = 0;
          {
            h_EXCEPTION_IN.close (0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
          CobolRuntimeException.code = 0;
          {
            h_REPORT_OUT.close (0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* src/CCREPT01.cob:34: MOVE */
        {
          b_RETURN_CODE.set((int)0);
        }
        /* src/CCREPT01.cob:34: GOBACK */
        {
          if(true) return Optional.of(contList[contList.length - 1]);
        }

        return Optional.of(contList[l_MAIN_SECTION__READ_AUDIT]);
      }
    },
    /* READ-AUDIT */
    new CobolControl(l_MAIN_SECTION__READ_AUDIT, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCREPT01.cob:36: PERFORM */
        for (;;)
        {
          if (((long)(Byte.toUnsignedInt(b_WS_AUDIT_EOF.getByte(0)) - (int)89) == 0L))
            break;
          {
            /* src/CCREPT01.cob:37: READ */
            CobolRuntimeException.code = 0;
            {
              h_AUDIT_IN.read (0, null, 1);
            }
            if (CobolRuntimeException.code != 0)
            {
              if (CobolRuntimeException.code == 0x0501)
              {
                {
                  /* src/CCREPT01.cob:38: MOVE */
                  {
                    b_WS_AUDIT_EOF.setByte(89);
                  }
                }
              }
              else
              {
                /* PERFORM Default Error Handler */
                CobolControl.perform(contList, l_Default_Error_Handler).run();
              }
            }
            else
            {
              {
                /* src/CCREPT01.cob:40: ADD */
                {
                  f_WS_AUDIT_COUNT.add (c_4_1, 4);
                }
                /* src/CCREPT01.cob:41: IF */
                {
                  if (((long)b_AUDIT_LINE.getSubDataStorage(24).memcmp (str_0_MANUAL_REVIEW, 13) == 0L))
                    {
                      /* src/CCREPT01.cob:42: ADD */
                      {
                        f_WS_REVIEW_COUNT.add (c_4_1, 4);
                      }
                    }
                }
              }
            }
          }
        }

        return Optional.of(contList[l_MAIN_SECTION__READ_EXCEPTIONS]);
      }
    },
    /* READ-EXCEPTIONS */
    new CobolControl(l_MAIN_SECTION__READ_EXCEPTIONS, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCREPT01.cob:47: PERFORM */
        for (;;)
        {
          if (((long)(Byte.toUnsignedInt(b_WS_EXC_EOF.getByte(0)) - (int)89) == 0L))
            break;
          {
            /* src/CCREPT01.cob:48: READ */
            CobolRuntimeException.code = 0;
            {
              h_EXCEPTION_IN.read (0, null, 1);
            }
            if (CobolRuntimeException.code != 0)
            {
              if (CobolRuntimeException.code == 0x0501)
              {
                {
                  /* src/CCREPT01.cob:49: MOVE */
                  {
                    b_WS_EXC_EOF.setByte(89);
                  }
                }
              }
              else
              {
                /* PERFORM Default Error Handler */
                CobolControl.perform(contList, l_Default_Error_Handler).run();
              }
            }
            else
            {
              {
                /* src/CCREPT01.cob:50: ADD */
                {
                  f_WS_EXCEPTION_COUNT.add (c_4_1, 4);
                }
              }
            }
          }
        }

        return Optional.of(contList[l_MAIN_SECTION__WRITE_REPORT]);
      }
    },
    /* WRITE-REPORT */
    new CobolControl(l_MAIN_SECTION__WRITE_REPORT, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/CCREPT01.cob:54: MOVE */
        {
          f_REPORT_LINE.moveFrom (c_5);
        }
        /* src/CCREPT01.cob:54: WRITE */
        CobolRuntimeException.code = 0;
        {
          h_REPORT_OUT.write (f_REPORT_LINE, 2162689, null);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }
        /* src/CCREPT01.cob:55: MOVE */
        {
          f_REPORT_LINE.moveFrom (c_6_CLAIMSCORE);
        }
        /* src/CCREPT01.cob:56: WRITE */
        CobolRuntimeException.code = 0;
        {
          h_REPORT_OUT.write (f_REPORT_LINE, 2162689, null);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }
        /* src/CCREPT01.cob:57: STRING */
        {
          CobolString.stringInit (f_REPORT_LINE, 0);
          CobolString.stringDelimited (0);
          CobolString.stringAppend (c_7_AUDIT);
          CobolString.stringAppend (f_WS_AUDIT_COUNT);
          CobolString.stringFinish ();
        }
        /* src/CCREPT01.cob:58: WRITE */
        CobolRuntimeException.code = 0;
        {
          h_REPORT_OUT.write (f_REPORT_LINE, 2162689, null);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }
        /* src/CCREPT01.cob:59: STRING */
        {
          CobolString.stringInit (f_REPORT_LINE, 0);
          CobolString.stringDelimited (0);
          CobolString.stringAppend (c_8_EXCEPTIONS);
          CobolString.stringAppend (f_WS_EXCEPTION_COUNT);
          CobolString.stringFinish ();
        }
        /* src/CCREPT01.cob:60: WRITE */
        CobolRuntimeException.code = 0;
        {
          h_REPORT_OUT.write (f_REPORT_LINE, 2162689, null);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }
        /* src/CCREPT01.cob:61: STRING */
        {
          CobolString.stringInit (f_REPORT_LINE, 0);
          CobolString.stringDelimited (0);
          CobolString.stringAppend (c_9_MANUAL);
          CobolString.stringAppend (f_WS_REVIEW_COUNT);
          CobolString.stringFinish ();
        }
        /* src/CCREPT01.cob:62: WRITE */
        CobolRuntimeException.code = 0;
        {
          h_REPORT_OUT.write (f_REPORT_LINE, 2162689, null);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }
        /* src/CCREPT01.cob:63: MOVE */
        {
          f_REPORT_LINE.moveFrom (c_10_STATUS);
        }
        /* src/CCREPT01.cob:64: WRITE */
        CobolRuntimeException.code = 0;
        {
          h_REPORT_OUT.write (f_REPORT_LINE, 2162689, null);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }


        return Optional.of(CobolControl.pure());
      }
    },
    /* Default Error Handler */
    new CobolControl(l_Default_Error_Handler, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        if ((CobolFile.errorFile.flag_select_features & CobolFile.COB_SELECT_FILE_STATUS) == 0) {
        	CobolFile.defaultErrorHandle ();
        	CobolStopRunException.stopRunAndThrow (1);
        }

        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new CCREPT01().CCREPT01_(0);
    CobolStopRunException.stopRun();
  }

  public CCREPT01()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : CCREPT01 */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_AUDIT_IN_record = new CobolDataStorage(220);	/* AUDIT-IN_record */
    b_EXCEPTION_IN_record = new CobolDataStorage(220);	/* EXCEPTION-IN_record */
    b_REPORT_OUT_record = new CobolDataStorage(160);	/* REPORT-OUT_record */
    b_WS_AUDIT_EOF = new CobolDataStorage(1);	/* WS-AUDIT-EOF */
    b_WS_EXC_EOF = new CobolDataStorage(1);	/* WS-EXC-EOF */
    b_WS_AUDIT_COUNT = new CobolDataStorage(7);	/* WS-AUDIT-COUNT */
    b_WS_EXCEPTION_COUNT = new CobolDataStorage(7);	/* WS-EXCEPTION-COUNT */
    b_WS_REVIEW_COUNT = new CobolDataStorage(7);	/* WS-REVIEW-COUNT */
    b_AUDIT_LINE = b_AUDIT_IN_record;
    b_REPORT_LINE = b_REPORT_OUT_record;

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : CCREPT01 */
    f_AUDIT_IN_record	= CobolFieldFactory.makeCobolField(220, b_AUDIT_IN_record, a_1_Alphanumeric);	/* AUDIT-IN_record */
    f_EXCEPTION_IN_record	= CobolFieldFactory.makeCobolField(220, b_EXCEPTION_IN_record, a_1_Alphanumeric);	/* EXCEPTION-IN_record */
    f_REPORT_LINE	= CobolFieldFactory.makeCobolField(160, b_REPORT_LINE, a_1_Alphanumeric);	/* REPORT-LINE */
    f_REPORT_OUT_record	= CobolFieldFactory.makeCobolField(160, b_REPORT_OUT_record, a_1_Alphanumeric);	/* REPORT-OUT_record */
    f_WS_AUDIT_COUNT	= CobolFieldFactory.makeCobolField(7, b_WS_AUDIT_COUNT, a_2_NumericDisplay_Digits7_Scale0);	/* WS-AUDIT-COUNT */
    f_WS_EXCEPTION_COUNT	= CobolFieldFactory.makeCobolField(7, b_WS_EXCEPTION_COUNT, a_2_NumericDisplay_Digits7_Scale0);	/* WS-EXCEPTION-COUNT */
    f_WS_REVIEW_COUNT	= CobolFieldFactory.makeCobolField(7, b_WS_REVIEW_COUNT, a_2_NumericDisplay_Digits7_Scale0);	/* WS-REVIEW-COUNT */

    /* End of fields */


    /* Constants */

    c_1_data	= CobolFieldFactory.makeCobolField(str_1_data, a_1_Alphanumeric);
    c_2_data	= CobolFieldFactory.makeCobolField(str_2_data, a_1_Alphanumeric);
    c_3_data	= CobolFieldFactory.makeCobolField(str_3_data, a_1_Alphanumeric);
    c_4_1	= CobolFieldFactory.makeCobolField(1, "1", a_3_NumericDisplay_Digits1_Scale0);
    c_5	= CobolFieldFactory.makeCobolField(str_4, a_4_AlphanumericAll);
    c_6_CLAIMSCORE	= CobolFieldFactory.makeCobolField(str_5_CLAIMSCORE, a_1_Alphanumeric);
    c_7_AUDIT	= CobolFieldFactory.makeCobolField(str_6_AUDIT, a_1_Alphanumeric);
    c_8_EXCEPTIONS	= CobolFieldFactory.makeCobolField(str_7_EXCEPTIONS, a_1_Alphanumeric);
    c_9_MANUAL	= CobolFieldFactory.makeCobolField(str_8_MANUAL, a_1_Alphanumeric);
    c_10_STATUS	= CobolFieldFactory.makeCobolField(str_9_STATUS, a_1_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_NumericDisplay_Digits7_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 7,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_4_AlphanumericAll = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC_ALL,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : CCREPT01 */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_AUDIT_IN_record;	/* AUDIT-IN_record */
  private CobolDataStorage b_EXCEPTION_IN_record;	/* EXCEPTION-IN_record */
  private CobolDataStorage b_REPORT_OUT_record;	/* REPORT-OUT_record */
  private CobolDataStorage b_WS_AUDIT_EOF;	/* WS-AUDIT-EOF */
  private CobolDataStorage b_WS_EXC_EOF;	/* WS-EXC-EOF */
  private CobolDataStorage b_WS_AUDIT_COUNT;	/* WS-AUDIT-COUNT */
  private CobolDataStorage b_WS_EXCEPTION_COUNT;	/* WS-EXCEPTION-COUNT */
  private CobolDataStorage b_WS_REVIEW_COUNT;	/* WS-REVIEW-COUNT */
  private CobolDataStorage b_AUDIT_LINE;
  private CobolDataStorage b_REPORT_LINE;

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : CCREPT01 */
  private AbstractCobolField f_AUDIT_IN_record;	/* AUDIT-IN_record */
  private AbstractCobolField f_EXCEPTION_IN_record;	/* EXCEPTION-IN_record */
  private AbstractCobolField f_REPORT_LINE;	/* REPORT-LINE */
  private AbstractCobolField f_REPORT_OUT_record;	/* REPORT-OUT_record */
  private AbstractCobolField f_WS_AUDIT_COUNT;	/* WS-AUDIT-COUNT */
  private AbstractCobolField f_WS_EXCEPTION_COUNT;	/* WS-EXCEPTION-COUNT */
  private AbstractCobolField f_WS_REVIEW_COUNT;	/* WS-REVIEW-COUNT */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_10_STATUS;
  private AbstractCobolField c_9_MANUAL;
  private AbstractCobolField c_8_EXCEPTIONS;
  private AbstractCobolField c_7_AUDIT;
  private AbstractCobolField c_6_CLAIMSCORE;
  private AbstractCobolField c_5;
  private AbstractCobolField c_4_1;
  private AbstractCobolField c_3_data;
  private AbstractCobolField c_2_data;
  private AbstractCobolField c_1_data;

  /* Attributes */

  private CobolFieldAttribute a_4_AlphanumericAll;
  private CobolFieldAttribute a_3_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_2_NumericDisplay_Digits7_Scale0;
  private CobolFieldAttribute a_1_Alphanumeric;



  /* String literals */
  public static final byte[] str_9_STATUS = CobolUtil.stringToBytes("STATUS: CLAIMS BATCH COMPLETED");
  public static final byte[] str_8_MANUAL = CobolUtil.stringToBytes("MANUAL REVIEWS        : ");
  public static final byte[] str_7_EXCEPTIONS = CobolUtil.stringToBytes("EXCEPTIONS            : ");
  public static final byte[] str_6_AUDIT = CobolUtil.stringToBytes("AUDIT RECORDS         : ");
  public static final byte[] str_5_CLAIMSCORE = CobolUtil.stringToBytes("CLAIMSCORE - END OF DAY CLAIMS REPORT");
  public static final byte[] str_4 = CobolUtil.stringToBytes("=");
  public static final byte[] str_3_data = CobolUtil.stringToBytes("data/out/eod-claims-report.txt");
  public static final byte[] str_2_data = CobolUtil.stringToBytes("data/out/claim-exceptions.dat");
  public static final byte[] str_1_data = CobolUtil.stringToBytes("data/out/claim-audit.dat");
  public static final byte[] str_0_MANUAL_REVIEW = CobolUtil.stringToBytes("MANUAL_REVIEW");
  /* File AUDIT-IN */
  private CobolFile		h_AUDIT_IN = null;
  private byte[]	h_AUDIT_IN_status = new byte[4];
  /* File EXCEPTION-IN */
  private CobolFile		h_EXCEPTION_IN = null;
  private byte[]	h_EXCEPTION_IN_status = new byte[4];
  /* File REPORT-OUT */
  private CobolFile		h_REPORT_OUT = null;
  private byte[]	h_REPORT_OUT_status = new byte[4];

  /* Sections and Labels */
  private final static int l_CCREPT01 = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN_SECTION = 3;
  private final static int l_MAIN_SECTION__READ_AUDIT = 4;
  private final static int l_MAIN_SECTION__READ_EXCEPTIONS = 5;
  private final static int l_MAIN_SECTION__WRITE_REPORT = 6;
  private final static int l_Default_Error_Handler = 7;

}
