spring.application.name=modernized
spring.datasource.url=${DB2_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.driverClassName=${DB2_DRIVER:org.h2.Driver}
spring.datasource.username=${DB2_USERNAME:sa}
spring.datasource.password=${DB2_PASSWORD:}
spring.batch.job.enabled=true
spring.batch.jdbc.initialize-schema=always